"use client";import{safeResponseJson}from"../lib/api/client";

import { useEffect, useMemo, useState } from "react";

const API = (process.env.NEXT_PUBLIC_API_URL?.trim() || "/api/backend/api/v1").replace(/\/$/, "");
type Customer = { id:string; customerCode:string; name:string; contactName?:string; phone?:string; email?:string; city?:string; country?:string; defaultCurrency:string; paymentTermDays:number; creditLimit:number; isActive:boolean; activeOrderCount:number; createdAt:string };
type Form = { id?:string; name:string; legalName:string; contactName:string; phone:string; email:string; taxOffice:string; taxNumber:string; addressLine1:string; addressLine2:string; district:string; city:string; postalCode:string; country:string; defaultCurrency:string; paymentTermDays:string; creditLimit:string; notes:string };
const empty:Form={name:"",legalName:"",contactName:"",phone:"",email:"",taxOffice:"",taxNumber:"",addressLine1:"",addressLine2:"",district:"",city:"",postalCode:"",country:"Türkiye",defaultCurrency:"TRY",paymentTermDays:"0",creditLimit:"0",notes:""};

export default function CustomersPage(){
  const [rows,setRows]=useState<Customer[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[currency,setCurrency]=useState(""),[form,setForm]=useState<Form|null>(null),[error,setError]=useState("");
  async function load(){const p=new URLSearchParams();if(search)p.set("search",search);if(status)p.set("isActive",status);if(currency)p.set("currency",currency);const r=await fetch(`${API}/customers?${p}`);const j=await safeResponseJson(r);setRows(j.data??[])}
  useEffect(()=>{void load()},[search,status,currency]);
  const cards=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.isActive).length,open:rows.filter(x=>x.activeOrderCount>0).length,newThisMonth:rows.filter(x=>new Date(x.createdAt).getMonth()===new Date().getMonth()).length}),[rows]);
  async function edit(id:string){const r=await fetch(`${API}/customers/${id}`),j=await safeResponseJson(r),x=j.data;setForm({id:x.id,name:x.companyName||x.name||"",legalName:x.legalName||"",contactName:x.contactName||"",phone:x.phone||"",email:x.email||"",taxOffice:x.taxOffice||"",taxNumber:x.taxNumber||"",addressLine1:x.addressLine1||"",addressLine2:x.addressLine2||"",district:x.district||"",city:x.city||"",postalCode:x.postalCode||"",country:x.country||"",defaultCurrency:x.defaultCurrency||"TRY",paymentTermDays:String(x.paymentTermDays??0),creditLimit:String(x.creditLimit??0),notes:x.notes||""})}
  async function save(){if(!form)return;setError("");const body={...form,paymentTermDays:Number(form.paymentTermDays),creditLimit:Number(form.creditLimit)};const r=await fetch(`${API}/customers${form.id?`/${form.id}`:""}`,{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await safeResponseJson(r);if(!r.ok){setError(j.message??"Kayıt başarısız.");return}setForm(null);await load()}
  async function toggle(x:Customer){await fetch(`${API}/customers/${x.id}/${x.isActive?"deactivate":"activate"}`,{method:"POST"});await load()}
  return <main className="min-h-screen bg-[#05070A] px-6 py-8 text-white"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex justify-between"><div><p className="text-xs font-black tracking-[.3em] text-emerald-400">CUSTOMER MASTER</p><h1 className="text-3xl font-black">Müşteriler</h1></div><button onClick={()=>setForm({...empty})} className="rounded-xl bg-emerald-500 px-5 py-3 font-black text-black">Yeni Müşteri</button></header>
    <section className="grid gap-4 md:grid-cols-4">{[["Toplam Müşteri",cards.total],["Aktif Müşteri",cards.active],["Açık Siparişi Olan",cards.open],["Bu Ay Yeni",cards.newThisMonth]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-zinc-400">{a}</p><p className="mt-2 text-3xl font-black">{b}</p></div>)}</section>
    <section className="flex flex-wrap gap-3 rounded-2xl border border-white/10 bg-white/5 p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Firma, kod ara" className="control"/><select value={status} onChange={e=>setStatus(e.target.value)} className="control"><option value="">Tüm durumlar</option><option value="true">Aktif</option><option value="false">Pasif</option></select><select value={currency} onChange={e=>setCurrency(e.target.value)} className="control"><option value="">Tüm para birimleri</option>{["TRY","EUR","USD","GBP"].map(x=><option key={x}>{x}</option>)}</select></section>
    <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="text-zinc-400">{["Kod","Firma","Yetkili","Telefon","E-posta","Şehir/Ülke","Para","Vade","Aktif Sipariş","Durum","İşlem"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr className="border-t border-white/10" key={x.id}><td className="p-4 font-mono text-emerald-300">{x.customerCode}</td><td className="p-4 font-bold">{x.name}</td><td className="p-4">{x.contactName||"-"}</td><td className="p-4">{x.phone||"-"}</td><td className="p-4">{x.email||"-"}</td><td className="p-4">{[x.city,x.country].filter(Boolean).join(" / ")||"-"}</td><td className="p-4">{x.defaultCurrency}</td><td className="p-4">{x.paymentTermDays} gün</td><td className="p-4">{x.activeOrderCount}</td><td className="p-4">{x.isActive?"Aktif":"Pasif"}</td><td className="p-4 space-x-2"><button onClick={()=>void edit(x.id)}>Düzenle</button><button onClick={()=>void toggle(x)}>{x.isActive?"Pasifleştir":"Aktifleştir"}</button></td></tr>)}</tbody></table></div>
  </div>{form&&<Modal title={form.id?"Müşteri Düzenle":"Yeni Müşteri"} error={error} close={()=>setForm(null)} save={()=>void save()}><div className="grid gap-3 md:grid-cols-2">{([['name','Firma Adı'],['legalName','Ticari Unvan'],['contactName','Yetkili'],['phone','Telefon'],['email','E-posta'],['taxOffice','Vergi Dairesi'],['taxNumber','Vergi Numarası'],['addressLine1','Adres'],['addressLine2','Adres 2'],['district','İlçe'],['city','Şehir'],['postalCode','Posta Kodu'],['country','Ülke'],['paymentTermDays','Vade Günü'],['creditLimit','Risk Limiti'],['notes','Notlar']] as [keyof Form,string][]).map(([k,l])=><label className="text-sm" key={k}><span className="text-zinc-400">{l}</span><input value={form[k]??""} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-lg border border-white/10 bg-black/40 p-2"/></label>)}<label><span className="text-zinc-400">Para Birimi</span><select value={form.defaultCurrency} onChange={e=>setForm({...form,defaultCurrency:e.target.value})} className="mt-1 w-full rounded-lg border border-white/10 bg-black p-2">{["TRY","EUR","USD","GBP"].map(x=><option key={x}>{x}</option>)}</select></label></div></Modal>}</main>
}
function Modal({title,error,close,save,children}:{title:string,error:string,close:()=>void,save:()=>void,children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><div className="max-h-[94vh] w-full max-w-4xl overflow-auto rounded-2xl border border-white/10 bg-[#0b0e13] p-6"><div className="mb-5 flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}>Kapat</button></div>{error&&<p className="mb-4 text-red-300">{error}</p>}{children}<div className="mt-6 text-right"><button onClick={save} className="rounded-xl bg-emerald-500 px-6 py-3 font-black text-black">Kaydet</button></div></div></div>}
