export type NavItem={href:string;label:string;permission:string};export type NavCategory={id:string;label:string;description:string;accent:string;items:NavItem[]};
export const navigation:NavCategory[]=[
{id:"management",label:"Yönetim",description:"Fabrikanın genel görünümü ve canlı operasyon yönetimi",accent:"emerald",items:[{href:"/dashboard",label:"Yönetim Dashboard’u",permission:"executive"},{href:"/live-production",label:"Canlı Üretim",permission:"production"},{href:"/production-planning",label:"Üretim Planlama",permission:"production"}]},
{id:"sales",label:"Satış ve Müşteriler",description:"Müşteri, teklif, sipariş ve tahsilat süreçleri",accent:"sky",items:[{href:"/customers",label:"Müşteriler",permission:"customers"},{href:"/quotes",label:"Teklifler",permission:"quotes"},{href:"/orders",label:"Satış Siparişleri",permission:"orders"},{href:"/customer-receivables",label:"Müşteri Alacakları",permission:"customer-finance"},{href:"/customer-collections",label:"Tahsilatlar",permission:"customer-finance"},{href:"/customer-ledger",label:"Müşteri Cari Hesabı",permission:"customer-finance"},{href:"/customer-cheques",label:"Müşteri Çekleri",permission:"cheques"}]},
{id:"products",label:"Ürün ve Reçeteler",description:"Ürün ağacı, reçete, kalıp ve maliyet ayarları",accent:"violet",items:[{href:"/products",label:"Ürünler",permission:"products"},{href:"/recipes",label:"Reçeteler / BOM",permission:"recipes"},{href:"/molds",label:"Kalıplar",permission:"production"},{href:"/cost-settings",label:"Maliyet Ayarları",permission:"costs"},{href:"/exchange-rates",label:"Döviz Kurları",permission:"costs"}]},
{id:"stock",label:"Stok ve Satın Alma",description:"Malzeme, lot, ambalaj ve tedarik yönetimi",accent:"amber",items:[{href:"/materials",label:"Hammadde ve Malzemeler",permission:"materials"},{href:"/stocks",label:"Stok ve Depo",permission:"stocks"},{href:"/material-lots",label:"Hammadde Lotları",permission:"lots"},{href:"/material-containers",label:"Varil / Ambalaj Takibi",permission:"containers"},{href:"/stock-reservations",label:"Stok Rezervasyonları",permission:"reservations"},{href:"/material-consumptions",label:"Hammadde Tüketimleri",permission:"consumption"},{href:"/purchases",label:"Satın Alma",permission:"purchases"},{href:"/suppliers",label:"Tedarikçiler",permission:"suppliers"}]},
{id:"production",label:"Üretim",description:"İş emirlerinden kalite ve kesime üretim operasyonları",accent:"orange",items:[{href:"/work-orders",label:"İş Emirleri",permission:"work-orders"},{href:"/machines",label:"Makineler",permission:"production"},{href:"/operators",label:"Operatörler",permission:"production"},{href:"/quality-control",label:"Kalite Kontrol",permission:"quality"},{href:"/cutting",label:"Kesim",permission:"cutting"},{href:"/production-boxes",label:"Üretim Kolileri",permission:"boxes"}]},
{id:"warehouse",label:"Depo ve Sevkiyat",description:"Mamul depo, sevkiyat ve uçtan uca izlenebilirlik",accent:"cyan",items:[{href:"/warehouse",label:"Mamul Deposu",permission:"warehouse"},{href:"/shipment",label:"Sevkiyat",permission:"shipments"},{href:"/traceability",label:"İzlenebilirlik / QR",permission:"traceability"}]},
{id:"finance",label:"Finans",description:"Kasa, banka, nakit akışı ve cari hesaplar",accent:"lime",items:[{href:"/finance",label:"Finans Yönetim Merkezi",permission:"cash-flow"},{href:"/financial-accounts",label:"Kasa ve Bankalar",permission:"financial-accounts"},{href:"/income-expense",label:"Gelir / Gider Kaydı",permission:"financial-accounts"},{href:"/financial-transactions",label:"Finansal Hareketler",permission:"financial-accounts"},{href:"/cash-flow",label:"Nakit Akışı",permission:"cash-flow"},{href:"/supplier-payables",label:"Tedarikçi Borçları",permission:"supplier-finance"},{href:"/supplier-payments",label:"Tedarikçi Ödemeleri",permission:"supplier-finance"},{href:"/supplier-ledger",label:"Tedarikçi Cari Hesabı",permission:"supplier-finance"},{href:"/cheque-endorsements",label:"Çek Ciro İşlemleri",permission:"supplier-finance"}]},
{id:"maintenance",label:"Bakım",description:"Arıza, bakım iş emri ve periyodik plan yönetimi",accent:"rose",items:[{href:"/maintenance",label:"Bakım Dashboard",permission:"maintenance"},{href:"/maintenance-requests",label:"Bakım Talepleri",permission:"maintenance-request"},{href:"/maintenance-work-orders",label:"Bakım İş Emirleri",permission:"maintenance"},{href:"/maintenance-assets",label:"Makine ve Varlıklar",permission:"maintenance"},{href:"/preventive-maintenance",label:"Periyodik Bakım",permission:"maintenance-plan"}]},
{id:"reports",label:"Raporlar",description:"Kârlılık ve gerçek üretim maliyeti analizleri",accent:"fuchsia",items:[{href:"/customer-profitability",label:"Müşteri Kârlılığı",permission:"profitability"},{href:"/order-profitability",label:"Sipariş Kârlılığı",permission:"profitability"},{href:"/product-profitability",label:"Ürün Kârlılığı",permission:"profitability"},{href:"/work-order-costs",label:"İş Emri Maliyetleri",permission:"costs"}]},
{id:"system",label:"Sistem",description:"Kullanıcı, erişim ve veri bütünlüğü yönetimi",accent:"zinc",items:[{href:"/system-control",label:"Sistem Kontrol Merkezi",permission:"system-control"},{href:"/users",label:"Kullanıcılar",permission:"users"}]}
];
