"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

const API = "http://localhost:5000/api/v1";
type Lot = { id:string; lotNumber:string; supplierLotNumber?:string; materialId:string; materialCode?:string; materialName:string; stockItemId:string; stockCode?:string; supplierName?:string; receivedDate:string; expiryDate?:string; initialQuantity:number; currentQuantity:number; reservedQuantity:number; availableQuantity:number; unit:string; warehouse?:string; rackCode?:string; status:string; qualityStatus:string; isBlocked:boolean; isActive:boolean; containerCount:number };
type Choice = { id:string; name:string; code?:string; materialId?:string; unit?:string };
type Summary = { total:number; available:number; qualityPending:number; blocked:number; expired:number; expiringSoon:number; depleted:number };
const input="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white";

export default function MaterialLotsPage(){
 const [lots,setLots]=useState<Lot[]>([]),[materials,setMaterials]=useState<Choice[]>([]),[stocks,setStocks]=useState<Choice[]>([]); const [summary,setSummary]=useState<Summary>({total:0,available:0,qualityPending:0,blocked:0,expired:0,expiringSoon:0,depleted:0}); const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[quality,setQuality]=useState(""); const [message,setMessage]=useState("");
 const [form,setForm]=useState({materialId:"",stockItemId:"",lotNumber:"",receivedDate:new Date().toISOString().slice(0,10),expiryDate:"",initialQuantity:"",unit:"",warehouse:"",rackCode:"",qualityStatus:"Pending",notes:""});
 async function load(){ const qs=new URLSearchParams(); if(search)qs.set("search",search);if(status)qs.set("status",status);if(quality)qs.set("qualityStatus",quality); const [a,b,c,d]=await Promise.all([fetch(`${API}/material-lots?${qs}`),fetch(`${API}/material-lots/summary`),fetch(`${API}/materials`),fetch(`${API}/stocks`)]); const [aj,bj,cj,dj]=await Promise.all([a.json(),b.json(),c.json(),d.json()]);setLots(aj.data??[]);setSummary(bj.data??summary);setMaterials(cj.data??[]);setStocks(dj.data??[]); }
 useEffect(()=>{void load()},[]); const matching=useMemo(()=>stocks.filter(x=>!form.materialId||x.materialId===form.materialId),[stocks,form.materialId]);
 async function create(e:FormEvent){e.preventDefault();const r=await fetch(`${API}/material-lots`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,initialQuantity:Number(form.initialQuantity),expiryDate:form.expiryDate||null})});const j=await r.json();setMessage(r.ok?"Lot oluşturuldu.":j.message??"Lot oluşturulamadı.");if(r.ok){setForm({...form,lotNumber:"",initialQuantity:"",expiryDate:"",notes:""});await load();}}
 async function action(id:string,name:string,reason?:string){const r=await fetch(`${API}/material-lots/${id}/${name}`,{method:"POST",headers:{"Content-Type":"application/json"},body:reason?JSON.stringify({reason}):undefined});const j=await r.json();setMessage(r.ok?"İşlem tamamlandı.":j.message??"İşlem yapılamadı.");if(r.ok)await load();}
 return <main className="min-h-screen bg-zinc-950 p-6 text-white"><div className="mx-auto max-w-7xl space-y-6">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-emerald-400">STOK İZLENEBİLİRLİĞİ</p><h1 className="text-3xl font-black">Hammadde Lotları</h1></div><div className="flex gap-2"><Link className={input} href="/stocks">Stoklar</Link><Link className={input} href="/material-containers">Varil / Ambalaj Takibi</Link></div></header>
  <section className="grid grid-cols-2 gap-3 md:grid-cols-7">{[["Toplam Lot",summary.total],["Kullanılabilir",summary.available],["Kalite Bekleyen",summary.qualityPending],["Blokeli",summary.blocked],["Süresi Geçen",summary.expired],["Yaklaşan",summary.expiringSoon],["Tükenen",summary.depleted]].map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-zinc-400">{k}</p><b className="text-2xl">{v}</b></div>)}</section>
  {message&&<p className="rounded-xl bg-emerald-500/10 p-3 text-emerald-300">{message}</p>}
  <form onSubmit={create} className="grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-5 md:grid-cols-5"><select required className={input} value={form.materialId} onChange={e=>setForm({...form,materialId:e.target.value,stockItemId:""})}><option value="">Malzeme seç</option>{materials.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><select required className={input} value={form.stockItemId} onChange={e=>{const s=stocks.find(x=>x.id===e.target.value);setForm({...form,stockItemId:e.target.value,unit:s?.unit??""})}}><option value="">Stok kartı seç</option>{matching.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input className={input} placeholder="Lot No (otomatik olabilir)" value={form.lotNumber} onChange={e=>setForm({...form,lotNumber:e.target.value})}/><input required className={input} type="number" step="0.001" placeholder="İlk miktar" value={form.initialQuantity} onChange={e=>setForm({...form,initialQuantity:e.target.value})}/><input className={input} readOnly placeholder="Birim" value={form.unit}/><input required className={input} type="date" value={form.receivedDate} onChange={e=>setForm({...form,receivedDate:e.target.value})}/><input className={input} type="date" value={form.expiryDate} onChange={e=>setForm({...form,expiryDate:e.target.value})}/><input className={input} placeholder="Depo" value={form.warehouse} onChange={e=>setForm({...form,warehouse:e.target.value})}/><input className={input} placeholder="Raf" value={form.rackCode} onChange={e=>setForm({...form,rackCode:e.target.value})}/><button className="rounded-xl bg-emerald-500 px-4 py-2 font-bold text-black">Lot Oluştur</button></form>
  <section className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="mb-4 flex flex-wrap gap-2"><input className={input} placeholder="Lot, batch veya malzeme ara" value={search} onChange={e=>setSearch(e.target.value)}/><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm durumlar</option>{["Available","PartiallyUsed","FullyUsed","Blocked","Expired","Cancelled"].map(x=><option key={x}>{x}</option>)}</select><select className={input} value={quality} onChange={e=>setQuality(e.target.value)}><option value="">Tüm kalite durumları</option>{["Pending","Approved","Conditional","Rejected"].map(x=><option key={x}>{x}</option>)}</select><button className={input} onClick={()=>void load()}>Filtrele</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-zinc-400"><tr>{["Lot No","Malzeme","Geliş/SKT","İlk","Mevcut","Rezerve","Kullanılabilir","Varil","Depo/Raf","Kalite","Durum","İşlemler"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{lots.map(x=><tr key={x.id} className="border-t border-white/10"><td className="p-2 font-bold">{x.lotNumber}</td><td className="p-2">{x.materialCode} · {x.materialName}</td><td className="p-2">{new Date(x.receivedDate).toLocaleDateString("tr-TR")}<br/>{x.expiryDate?new Date(x.expiryDate).toLocaleDateString("tr-TR"):"-"}</td><td className="p-2">{x.initialQuantity} {x.unit}</td><td className="p-2">{x.currentQuantity}</td><td className="p-2">{x.reservedQuantity}</td><td className="p-2">{x.availableQuantity}</td><td className="p-2"><Link className="text-cyan-300" href={`/material-containers?lotId=${x.id}`}>{x.containerCount}</Link></td><td className="p-2">{x.warehouse??"-"}/{x.rackCode??"-"}</td><td className="p-2">{x.qualityStatus}</td><td className="p-2">{x.status}{!x.isActive?" · Pasif":""}</td><td className="p-2"><div className="flex flex-wrap gap-1"><button onClick={()=>void action(x.id,x.qualityStatus==="Approved"?"reject-quality":"approve-quality")} className={input}>Kalite</button><button onClick={()=>void action(x.id,x.isBlocked?"unblock":"block",x.isBlocked?undefined:"Operasyon blokesi")} className={input}>{x.isBlocked?"Blokeyi kaldır":"Bloke et"}</button>{x.isActive&&<button onClick={()=>void action(x.id,"deactivate")} className={input}>Pasifleştir</button>}</div></td></tr>)}</tbody></table></div></section>
 </div></main>
}
