"use client";import{safeResponseJson}from"../lib/api/client";
import { useEffect,useMemo,useState } from "react";
import { uiLabel } from "../lib/ui/labels";
const API=(process.env.NEXT_PUBLIC_API_URL?.trim()||"/api/backend/api/v1").replace(/\/$/,"");
type Customer={id:string;customerCode:string;name:string;defaultCurrency:string;paymentTermDays:number}; type Product={id:string;code:string;name:string};
type Order={id:string;orderNumber:string;orderDate:string;customerId:string;customerName:string;currency:string;expectedPaymentMethod:string;paymentTermDays:number;dueDate?:string;itemCount:number;totalPairs:number;producedPairs:number;cutPairs:number;shippedPairs:number;grandTotal:number;status:string};
type Item={id:string;productId:string;moldId:string;productionType:string;fabricColor:string;sizeRange:string;color:string;quantityPairs:string;unitPrice:string;discountPercent:string;taxPercent:string;requestedDeliveryDate:string;note:string};
const item=():Item=>({id:"00000000-0000-0000-0000-000000000000",productId:"",moldId:"",productionType:"",fabricColor:"",sizeRange:"",color:"",quantityPairs:"",unitPrice:"0",discountPercent:"0",taxPercent:"0",requestedDeliveryDate:"",note:""});
export default function OrdersPage(){const [orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[filter,setFilter]=useState(""),[status,setStatus]=useState(""),[form,setForm]=useState<any>(null),[error,setError]=useState("");
async function load(){const [a,b,c]=await Promise.all([fetch(`${API}/orders`),fetch(`${API}/customers?isActive=true`),fetch(`${API}/products`)]);const [aj,bj,cj]=await Promise.all([safeResponseJson(a),safeResponseJson(b),safeResponseJson(c)]);setOrders(aj.data??[]);setCustomers(bj.data??[]);setProducts(Array.isArray(cj.data)?cj.data:(cj.data?.items??[]))}useEffect(()=>{void load()},[]);
const shown=orders.filter(x=>(!filter||(x.orderNumber+x.customerName).toLowerCase().includes(filter.toLowerCase()))&&(!status||x.status===status));const sums=useMemo(()=>({open:orders.filter(x=>!["Completed","Cancelled"].includes(x.status)).length,total:orders.reduce((a,x)=>a+x.totalPairs,0),produced:orders.reduce((a,x)=>a+x.producedPairs,0),shipped:orders.reduce((a,x)=>a+x.shippedPairs,0),late:orders.filter(x=>x.dueDate&&new Date(x.dueDate)<new Date()&&!["Completed","Cancelled"].includes(x.status)).length}),[orders]);
function create(){setForm({customerId:"",orderDate:new Date().toISOString().slice(0,10),dueDate:"",customerReference:"",currency:"TRY",expectedPaymentMethod:"OpenAccount",paymentTermDays:"0",discountPercent:"0",taxPercent:"0",notes:"",items:[item()]})}
async function edit(id:string){const r=await fetch(`${API}/orders/${id}`),j=await safeResponseJson(r),x=j.data;setForm({id:x.id,customerId:x.customerId,orderDate:x.orderDate.slice(0,10),dueDate:x.dueDate?.slice(0,10)??"",customerReference:x.customerReference??"",currency:x.currency,expectedPaymentMethod:x.expectedPaymentMethod,paymentTermDays:String(x.paymentTermDays),discountPercent:String(x.discountPercent),taxPercent:String(x.taxPercent),notes:x.notes??"",items:x.items.filter((i:any)=>i.isActive&&!i.isCancelled).map((i:any)=>({id:i.id,productId:i.productId,moldId:i.moldId??"",productionType:i.productionType??"",fabricColor:i.fabricColor??"",sizeRange:i.sizeRange??"",color:i.color??"",quantityPairs:String(i.quantityPairs),unitPrice:String(i.unitPrice),discountPercent:String(i.discountPercent),taxPercent:String(i.taxPercent),requestedDeliveryDate:i.requestedDeliveryDate?.slice(0,10)??"",note:i.note??""}))})}
function update(k:string,v:any){setForm({...form,[k]:v})}function updateItem(i:number,k:string,v:string){const items=[...form.items];items[i]={...items[i],[k]:v};setForm({...form,items})}
async function save(){setError("");const body={...form,paymentTermDays:Number(form.paymentTermDays),discountPercent:Number(form.discountPercent),taxPercent:Number(form.taxPercent),dueDate:form.dueDate||null,items:form.items.map((x:Item)=>({...x,moldId:x.moldId||null,quantityPairs:Number(x.quantityPairs),unitPrice:Number(x.unitPrice),discountPercent:Number(x.discountPercent),taxPercent:Number(x.taxPercent),requestedDeliveryDate:x.requestedDeliveryDate||null}))};const r=await fetch(`${API}/orders${form.id?`/${form.id}`:""}`,{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await safeResponseJson(r);if(!r.ok){setError(j.message??"Sipariş kaydedilemedi.");return}setForm(null);await load()}
async function action(id:string,path:string,body?:unknown){const r=await fetch(`${API}/orders/${id}/${path}`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:body?JSON.stringify(body):undefined});if(!r.ok){const j=await safeResponseJson(r);alert(j.message??"İşlem başarısız.")}await load()}
return <main className="min-h-screen bg-[#05070A] px-6 py-8 text-white"><div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black tracking-[.3em] text-cyan-400">SATIŞ SİPARİŞİ YÖNETİMİ</p><h1 className="text-3xl font-black">Satış Siparişleri</h1></div><button onClick={create} className="rounded-xl bg-cyan-500 px-5 py-3 font-black text-black">Yeni Sipariş</button></header>
<section className="grid gap-3 md:grid-cols-5">{[["Açık Sipariş",sums.open],["Toplam Çift",sums.total],["Üretilen",sums.produced],["Sevk Edilen",sums.shipped],["Geciken",sums.late]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-zinc-400">{a}</p><p className="text-3xl font-black">{Number(b).toLocaleString("tr-TR")}</p></div>)}</section>
<section className="flex flex-wrap gap-3 rounded-2xl border border-white/10 bg-white/5 p-4"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Sipariş no / müşteri" className="min-w-0 flex-1 rounded-lg bg-black/40 p-3"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg bg-black p-3"><option value="">Tüm durumlar</option>{["Draft","Confirmed","InProduction","PartiallyCompleted","Completed","Cancelled","Aktif"].map(x=><option key={x} value={x}>{uiLabel(x)}</option>)}</select></section>
<div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/5"><table className="w-full min-w-[1450px] text-left text-sm"><thead><tr className="text-zinc-400">{["Sipariş No","Tarih","Müşteri","Kalem","Toplam","Üretilen","Kesilen","Sevk","Teslim","Para","Tutar","Ödeme","Durum","İşlem"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(x=><tr className="border-t border-white/10" key={x.id}><td className="p-3 font-mono text-cyan-300">{x.orderNumber}</td><td className="p-3">{date(x.orderDate)}</td><td className="p-3 font-bold">{x.customerName}</td><td className="p-3">{x.itemCount}</td><td className="p-3">{x.totalPairs}</td><td className="p-3">{x.producedPairs}</td><td className="p-3">{x.cutPairs}</td><td className="p-3">{x.shippedPairs}</td><td className="p-3">{date(x.dueDate)}</td><td className="p-3">{x.currency}</td><td className="p-3">{money(x.grandTotal,x.currency)}</td><td className="p-3">{payment(x.expectedPaymentMethod)} / {x.paymentTermDays} gün</td><td className="p-3">{uiLabel(x.status)}</td><td className="p-3 space-x-2">{["Draft","Aktif"].includes(x.status)&&<button onClick={()=>void action(x.id,"confirm")}>Onayla</button>}<button onClick={()=>void action(x.id,"duplicate")}>Çoğalt</button>{!["Cancelled","Completed"].includes(x.status)&&<button onClick={()=>{const reason=prompt("İptal nedeni");if(reason)void action(x.id,"cancel",{reason})}}>İptal</button>}</td></tr>)}</tbody></table></div></div>
{form&&<div className="fixed inset-0 z-50 overflow-auto bg-black/85 p-5"><div className="mx-auto max-w-6xl rounded-2xl border border-white/10 bg-[#0b0e13] p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">Yeni Satış Siparişi</h2><button onClick={()=>setForm(null)}>Kapat</button></div>{error&&<p className="my-3 text-red-300">{error}</p>}<div className="mt-5 grid gap-3 md:grid-cols-4"><Select label="Müşteri" value={form.customerId} set={v=>{const c=customers.find(x=>x.id===v);setForm({...form,customerId:v,currency:c?.defaultCurrency??"TRY",paymentTermDays:String(c?.paymentTermDays??0)})}} options={customers.map(x=>[x.id,`${x.customerCode} - ${x.name}`])}/><Input label="Sipariş Tarihi" type="date" value={form.orderDate} set={v=>update("orderDate",v)}/><Input label="Teslim Tarihi" type="date" value={form.dueDate} set={v=>update("dueDate",v)}/><Input label="Müşteri Referansı" value={form.customerReference} set={v=>update("customerReference",v)}/><Select label="Para Birimi" value={form.currency} set={v=>update("currency",v)} options={["TRY","EUR","USD","GBP"].map(x=>[x,x])}/><Select label="Beklenen Ödeme" value={form.expectedPaymentMethod} set={v=>update("expectedPaymentMethod",v)} options={[["Cash","Nakit"],["BankTransfer","Havale / EFT"],["CreditCard","Kredi Kartı"],["Cheque","Çek"],["OpenAccount","Cari Hesap"]]}/><Input label="Vade Günü" value={form.paymentTermDays} set={v=>update("paymentTermDays",v)}/><Input label="Sipariş İskonto %" value={form.discountPercent} set={v=>update("discountPercent",v)}/></div>
<div className="mt-6 space-y-4">{form.items.map((x:Item,i:number)=><div key={i} className="grid gap-3 rounded-xl border border-white/10 p-4 md:grid-cols-5"><Select label="Ürün" value={x.productId} set={v=>updateItem(i,"productId",v)} options={products.map(p=>[p.id,`${p.code} - ${p.name}`])}/>{([['productionType','Üretim Tipi'],['fabricColor','Kumaş Rengi'],['sizeRange','Numara Aralığı'],['color','Renk'],['quantityPairs','Çift'],['unitPrice','Birim Fiyat'],['discountPercent','İskonto %'],['taxPercent','KDV %'],['requestedDeliveryDate','Teslim Tarihi'],['note','Not']] as [keyof Item,string][]).map(([k,l])=><Input key={k} label={l} type={k==='requestedDeliveryDate'?'date':'text'} value={x[k]} set={v=>updateItem(i,k,v)}/>)}</div>)}</div><button className="mt-3" onClick={()=>setForm({...form,items:[...form.items,item()]})}>+ Kalem Ekle</button><div className="mt-6 text-right"><button onClick={()=>void save()} className="rounded-xl bg-cyan-500 px-7 py-3 font-black text-black">Siparişi Kaydet</button></div></div></div>}</main>}
function Input({label,value,set,type="text"}:{label:string,value:string,set:(x:string)=>void,type?:string}){return <label className="text-sm"><span className="text-zinc-400">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-black/40 p-2"/></label>};function Select({label,value,set,options}:{label:string,value:string,set:(x:string)=>void,options:string[][]}){return <label className="text-sm"><span className="text-zinc-400">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-black p-2"><option value="">Seçin</option>{options.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>};function date(x?:string){return x?new Date(x).toLocaleDateString("tr-TR"):"-"}function money(x:number,c:string){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:c}).format(x)}function payment(x:string){return ({Cash:"Nakit",BankTransfer:"Havale / EFT",CreditCard:"Kredi Kartı",Cheque:"Çek",OpenAccount:"Cari Hesap"} as Record<string,string>)[x]??x}
