using Asp.Versioning;using Fixar.API.Security;using Fixar.Application.Common.Models;using Fixar.Domain.Entities;using Fixar.Infrastructure.Identity;using Fixar.Infrastructure.Persistence;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;namespace Fixar.API.Controllers;
[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/cheque-endorsements"),Authorize(Policy=AuthorizationPolicies.CanViewSupplierFinance)]public class ChequeEndorsementsController(ApplicationDbContext db):ControllerBase{
[HttpGet]public async Task<IActionResult>List(CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(await db.ChequeEndorsements.AsNoTracking().OrderByDescending(x=>x.EndorsementDate).Select(x=>new{x.Id,x.EndorsementNumber,x.CustomerChequeId,x.CustomerCheque.PortfolioNumber,x.CustomerCheque.ChequeNumber,CustomerName=x.CustomerCheque.Customer.Name,x.SupplierId,SupplierName=x.Supplier.Name,x.SupplierPaymentId,x.EndorsementDate,x.CustomerCheque.DueDate,x.Currency,x.Amount,x.Status,x.ReferenceNumber}).ToListAsync(ct)));
[HttpGet("{id:guid}")]public async Task<IActionResult>Detail(Guid id,CancellationToken ct){var x=await db.ChequeEndorsements.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.EndorsementNumber,x.CustomerChequeId,x.SupplierId,x.SupplierPaymentId,x.EndorsementDate,x.Currency,x.Amount,x.Status,x.ReferenceNumber,x.Notes,x.IsReversed,x.ReversedAt,x.ReversalReason}).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(ApiResponse<object>.SuccessResponse(x));}
[HttpPost("{id:guid}/return"),Authorize(Policy=AuthorizationPolicies.CanManageChequeEndorsements),Idempotent]public Task<IActionResult>Return(Guid id,EndorsementAction r,CancellationToken ct)=>Undo(id,r,"Returned",false,ct);
[HttpPost("{id:guid}/reverse"),Authorize(Policy=AuthorizationPolicies.CanManageChequeEndorsements),Idempotent]public Task<IActionResult>Reverse(Guid id,EndorsementAction r,CancellationToken ct)=>Undo(id,r,"Reversed",false,ct);
[HttpPost("{id:guid}/bounce"),Authorize(Policy=AuthorizationPolicies.CanManageChequeEndorsements),Idempotent]public Task<IActionResult>Bounce(Guid id,EndorsementAction r,CancellationToken ct)=>Undo(id,r,"Returned",true,ct);
[HttpGet("summary")]public async Task<IActionResult>Summary(CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(await db.ChequeEndorsements.AsNoTracking().GroupBy(x=>new{x.Currency,x.Status}).Select(g=>new{g.Key.Currency,g.Key.Status,Amount=g.Sum(x=>x.Amount),Count=g.Count()}).ToListAsync(ct)));
async Task<IActionResult>Undo(Guid id,EndorsementAction r,string status,bool bounce,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("Gerekçe zorunludur.","REASON"));await using var tx=await db.Database.BeginTransactionAsync(ct);var e=await db.ChequeEndorsements.Include(x=>x.CustomerCheque).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(e.Status!="Active")return Conflict(ApiResponse<object>.Fail("Ciro daha önce kapatılmış.","TERMINAL"));var p=await db.SupplierPayments.Include(x=>x.Allocations).ThenInclude(x=>x.SupplierPayable).FirstAsync(x=>x.Id==e.SupplierPaymentId,ct);foreach(var a in p.Allocations.Where(x=>!x.IsReversed)){a.IsReversed=true;a.ReversedAt=DateTime.UtcNow;a.SupplierPayable.AllocatedAmount-=a.AllocatedAmount;a.SupplierPayable.OutstandingAmount+=a.AllocatedAmount;a.SupplierPayable.Status=SupplierFinanceSupport.Status(a.SupplierPayable);}db.SupplierLedgerEntries.Add(new SupplierLedgerEntry{Id=Guid.NewGuid(),EntryNumber=await SupplierFinanceSupport.Next(db,"SLE",DateTime.UtcNow,ct),SupplierId=p.SupplierId,TransactionDate=DateTime.UtcNow,EntryType="Credit",SourceType="Reversal",SourceId=p.Id,ReferenceNumber=p.PaymentNumber,Currency=p.Currency,CreditAmount=p.Amount,Description=r.Reason,Created=DateTime.UtcNow});p.IsReversed=true;p.Status="Reversed";p.ReversalReason=r.Reason;e.Status=status;e.IsReversed=status=="Reversed";e.ReversedAt=DateTime.UtcNow;e.ReversalReason=r.Reason;var ch=e.CustomerCheque;var previous=ch.Status;ch.Status=bounce?"Bounced":"InPortfolio";ch.EndorsedSupplierId=null;ch.SupplierPaymentId=null;ch.EndorsementNotes=r.Reason;db.ChequeEvents.Add(new ChequeEvent{Id=Guid.NewGuid(),CustomerChequeId=ch.Id,EventType=bounce?"Bounced":"EndorsementReturned",EventDate=DateTime.UtcNow,PreviousStatus=previous,NewStatus=ch.Status,Reason=r.Reason,Created=DateTime.UtcNow});if(bounce&&!await db.CustomerLedgerEntries.AnyAsync(x=>x.SourceType=="ChequeBounce"&&x.SourceId==ch.Id,ct)){db.CustomerLedgerEntries.Add(new CustomerLedgerEntry{Id=Guid.NewGuid(),EntryNumber=await CustomerFinanceSupport.NextNumber(db,"LED",DateTime.UtcNow,ct),CustomerId=ch.CustomerId,TransactionDate=DateTime.UtcNow,EntryType="Debit",SourceType="ChequeBounce",SourceId=ch.Id,ReferenceNumber=ch.PortfolioNumber,Currency=ch.Currency,DebitAmount=ch.Amount,Description=r.Reason,Created=DateTime.UtcNow});}await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{e.Id,e.Status,ChequeStatus=ch.Status,PaymentStatus=p.Status}));}}
public record EndorsementAction(string Reason);
