using Asp.Versioning;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Infrastructure.Identity;
using Fixar.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fixar.API.Controllers;

[ApiController, ApiVersion("1.0"), Authorize(Policy = AuthorizationPolicies.CanManageCostSettings)]
[Route("api/v{version:apiVersion}/cost-settings")]
public sealed class CostSettingsController(ApplicationDbContext db) : ControllerBase
{
    [HttpGet] public async Task<IActionResult> List(CancellationToken ct) => Ok(ApiResponse<object>.SuccessResponse(await db.CostSettings.AsNoTracking().OrderByDescending(x => x.EffectiveFrom).ToListAsync(ct)));
    [HttpGet("current")] public async Task<IActionResult> Current(DateTime? at, CancellationToken ct) { var date = at ?? DateTime.UtcNow; var x = await db.CostSettings.AsNoTracking().Where(x => x.IsActive && x.EffectiveFrom <= date && (x.EffectiveTo == null || x.EffectiveTo >= date)).OrderByDescending(x => x.EffectiveFrom).FirstOrDefaultAsync(ct); return x is null ? NotFound(ApiResponse<object>.Fail("Maliyet ayarı bulunamadı.", "COST_SETTINGS_NOT_FOUND")) : Ok(ApiResponse<object>.SuccessResponse(x)); }
    [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id, CancellationToken ct) { var x = await db.CostSettings.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, ct); return x is null ? NotFound(ApiResponse<object>.Fail("Maliyet ayarı bulunamadı.", "COST_SETTINGS_NOT_FOUND")) : Ok(ApiResponse<object>.SuccessResponse(x)); }
    [HttpPost] public async Task<IActionResult> Create(CostSettingsRequest request, CancellationToken ct) { var error = Validate(request); if (error is not null) return BadRequest(ApiResponse<object>.Fail(error, "VALIDATION_ERROR")); if (request.IsActive && await db.CostSettings.AnyAsync(y => y.IsActive && y.EffectiveFrom <= (request.EffectiveTo ?? DateTime.MaxValue) && (y.EffectiveTo == null || y.EffectiveTo >= request.EffectiveFrom), ct)) return Conflict(ApiResponse<object>.Fail("Aynı tarih aralığında başka bir aktif maliyet ayarı var.", "COST_SETTINGS_OVERLAP")); var x = new CostSettings(); Apply(x, request); db.CostSettings.Add(x); await db.SaveChangesAsync(ct); return CreatedAtAction(nameof(Get), new { id = x.Id, version = "1" }, ApiResponse<object>.SuccessResponse(new { x.Id }, "Maliyet ayarı oluşturuldu.")); }
    [HttpPut("{id:guid}")] public async Task<IActionResult> Update(Guid id, CostSettingsRequest request, CancellationToken ct) { var x = await db.CostSettings.FirstOrDefaultAsync(x => x.Id == id, ct); if (x is null) return NotFound(ApiResponse<object>.Fail("Maliyet ayarı bulunamadı.", "COST_SETTINGS_NOT_FOUND")); var error = Validate(request); if (error is not null) return BadRequest(ApiResponse<object>.Fail(error, "VALIDATION_ERROR")); Apply(x, request); await db.SaveChangesAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(new { x.Id }, "Maliyet ayarı güncellendi.")); }
    [HttpPost("{id:guid}/activate")] public Task<IActionResult> Activate(Guid id, CancellationToken ct) => SetActive(id, true, ct);
    [HttpPost("{id:guid}/deactivate")] public Task<IActionResult> Deactivate(Guid id, CancellationToken ct) => SetActive(id, false, ct);
    private async Task<IActionResult> SetActive(Guid id, bool active, CancellationToken ct) { var x = await db.CostSettings.FirstOrDefaultAsync(x => x.Id == id, ct); if (x is null) return NotFound(ApiResponse<object>.Fail("Maliyet ayarı bulunamadı.", "COST_SETTINGS_NOT_FOUND")); if (active && await db.CostSettings.AnyAsync(y => y.Id != id && y.IsActive && y.EffectiveFrom <= (x.EffectiveTo ?? DateTime.MaxValue) && (y.EffectiveTo == null || y.EffectiveTo >= x.EffectiveFrom), ct)) return Conflict(ApiResponse<object>.Fail("Aynı tarih aralığında başka bir aktif maliyet ayarı var.", "COST_SETTINGS_OVERLAP")); x.IsActive = active; await db.SaveChangesAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(new { x.Id, x.IsActive })); }
    private static string? Validate(CostSettingsRequest x) => string.IsNullOrWhiteSpace(x.Name) ? "Ayar adı zorunludur." : x.EffectiveTo < x.EffectiveFrom ? "Geçerlilik bitiş tarihi başlangıçtan önce olamaz." : new[] { x.DefaultHourlyLaborCost, x.DefaultEnergyCostPerKwh, x.DefaultMachineCostPerHour, x.DefaultOverheadRatePercent, x.DefaultCuttingCostPerPair, x.DefaultPackagingCostPerPair, x.DefaultQualityCostPerPair, x.DefaultShipmentPreparationCostPerBox }.Any(v => v < 0) ? "Maliyet değerleri negatif olamaz." : null;
    private static void Apply(CostSettings x, CostSettingsRequest r) { x.Name = r.Name.Trim(); x.EffectiveFrom = r.EffectiveFrom; x.EffectiveTo = r.EffectiveTo; x.ReportingCurrency = r.ReportingCurrency.Trim().ToUpperInvariant(); x.DefaultHourlyLaborCost = r.DefaultHourlyLaborCost; x.DefaultEnergyCostPerKwh = r.DefaultEnergyCostPerKwh; x.DefaultMachineCostPerHour = r.DefaultMachineCostPerHour; x.DefaultOverheadRatePercent = r.DefaultOverheadRatePercent; x.DefaultFireCostMethod = r.DefaultFireCostMethod; x.DefaultCuttingCostPerPair = r.DefaultCuttingCostPerPair; x.DefaultPackagingCostPerPair = r.DefaultPackagingCostPerPair; x.DefaultQualityCostPerPair = r.DefaultQualityCostPerPair; x.DefaultShipmentPreparationCostPerBox = r.DefaultShipmentPreparationCostPerBox; x.Notes = r.Notes; x.IsActive = r.IsActive; }
}
public sealed record CostSettingsRequest(string Name, DateTime EffectiveFrom, DateTime? EffectiveTo, string ReportingCurrency, decimal DefaultHourlyLaborCost, decimal DefaultEnergyCostPerKwh, decimal DefaultMachineCostPerHour, decimal DefaultOverheadRatePercent, string DefaultFireCostMethod, decimal DefaultCuttingCostPerPair, decimal DefaultPackagingCostPerPair, decimal DefaultQualityCostPerPair, decimal DefaultShipmentPreparationCostPerBox, string? Notes, bool IsActive);
