using Asp.Versioning;
using Fixar.API.Security;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Infrastructure.Identity;
using Fixar.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace Fixar.API.Controllers;

[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/customer-collections"),Authorize(Policy=AuthorizationPolicies.CanViewCustomerFinance)]
public class CustomerCollectionsController(ApplicationDbContext db):ControllerBase
{
    private static readonly string[] Methods=["Cash","BankTransfer","CreditCard","Cheque","Other"];
    [HttpGet] public async Task<IActionResult> List(Guid? customerId,string? paymentMethod,string? status,string? currency,bool? isReversed,DateTime? dateFrom,DateTime? dateTo,string? search,CancellationToken ct){var q=db.CustomerCollections.AsNoTracking().AsQueryable();if(customerId.HasValue)q=q.Where(x=>x.CustomerId==customerId);if(!string.IsNullOrWhiteSpace(paymentMethod))q=q.Where(x=>x.PaymentMethod==paymentMethod);if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(currency))q=q.Where(x=>x.Currency==currency.ToUpper());if(isReversed.HasValue)q=q.Where(x=>x.IsReversed==isReversed);if(dateFrom.HasValue)q=q.Where(x=>x.CollectionDate>=dateFrom);if(dateTo.HasValue)q=q.Where(x=>x.CollectionDate<=dateTo);if(!string.IsNullOrWhiteSpace(search)){var s=search.ToLower();q=q.Where(x=>x.CollectionNumber.ToLower().Contains(s)||x.Customer.Name.ToLower().Contains(s)||(x.ReferenceNumber!=null&&x.ReferenceNumber.ToLower().Contains(s)));}var rows=await q.OrderByDescending(x=>x.CollectionDate).Select(x=>new{x.Id,x.CollectionNumber,x.CustomerId,CustomerCode=x.Customer.CustomerCode,CustomerName=x.Customer.CompanyName??x.Customer.Name,x.CollectionDate,x.Currency,x.Amount,x.PaymentMethod,x.ReferenceNumber,x.BankReference,x.Status,x.UnallocatedAmount,AllocatedAmount=x.Amount-x.UnallocatedAmount,x.IsReversed,x.Notes,x.FinancialAccountId,x.FinancialTransactionId,x.CustomerChequeId,x.FinancePostingStatus,x.FinancePostingWarning}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("{id:guid}")]public async Task<IActionResult> Detail(Guid id,CancellationToken ct){var x=await db.CustomerCollections.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.CollectionNumber,x.CustomerId,CustomerName=x.Customer.CompanyName??x.Customer.Name,x.CollectionDate,x.Currency,x.Amount,x.PaymentMethod,x.ReferenceNumber,x.BankReference,x.Notes,x.Status,x.UnallocatedAmount,x.IsReversed,x.ReversedAt,x.ReversedBy,x.ReversalReason,x.FinancialAccountId,x.FinancialTransactionId,x.CustomerChequeId,x.FinancePostingStatus,x.FinancePostingWarning,Allocations=x.Allocations.Select(a=>new CollectionAllocationDto(a.Id,a.CustomerCollectionId,x.CollectionNumber,a.CustomerReceivableId,a.AllocatedAmount,a.Currency,a.AllocationDate,a.Notes,a.IsReversed))}).FirstOrDefaultAsync(ct);return x is null?NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND")):Ok(ApiResponse<object>.SuccessResponse(x));}
    [HttpGet("customer/{customerId:guid}")]public Task<IActionResult> Customer(Guid customerId,CancellationToken ct)=>List(customerId,null,null,null,null,null,null,null,ct);
    [HttpPost,Authorize(Policy=AuthorizationPolicies.CanRecordCollections)]public async Task<IActionResult>Create(CollectionRequest r,CancellationToken ct){var error=await Validate(r,ct);if(error!=null)return BadRequest(ApiResponse<object>.Fail(error,"VALIDATION_ERROR"));await using var tx=await db.Database.BeginTransactionAsync(ct);var x=new CustomerCollection{Id=Guid.NewGuid(),CollectionNumber=await CustomerFinanceSupport.NextNumber(db,"COL",r.CollectionDate,ct),CustomerId=r.CustomerId,CollectionDate=r.CollectionDate.ToUniversalTime(),Currency=r.Currency.ToUpper(),Amount=r.Amount,UnallocatedAmount=r.Amount,PaymentMethod=r.PaymentMethod,ReferenceNumber=r.ReferenceNumber,BankReference=r.BankReference,Notes=r.Notes,Status="Draft"};db.CustomerCollections.Add(x);CustomerFinanceSupport.Audit(db,this,"Customer Collection Created",x.Id,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.CollectionNumber,x.Status},"Taslak tahsilat oluşturuldu."));}
    [HttpPut("{id:guid}"),Authorize(Policy=AuthorizationPolicies.CanRecordCollections)]public async Task<IActionResult>Update(Guid id,CollectionRequest r,CancellationToken ct){var x=await db.CustomerCollections.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND"));if(x.Status!="Draft")return Conflict(ApiResponse<object>.Fail("Yalnız taslak tahsilat düzenlenebilir.","COLLECTION_LOCKED"));var error=await Validate(r,ct);if(error!=null)return BadRequest(ApiResponse<object>.Fail(error,"VALIDATION_ERROR"));x.CustomerId=r.CustomerId;x.CollectionDate=r.CollectionDate.ToUniversalTime();x.Currency=r.Currency.ToUpper();x.Amount=r.Amount;x.UnallocatedAmount=r.Amount;x.PaymentMethod=r.PaymentMethod;x.ReferenceNumber=r.ReferenceNumber;x.BankReference=r.BankReference;x.Notes=r.Notes;CustomerFinanceSupport.Audit(db,this,"Customer Collection Updated",x.Id,r);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status},"Tahsilat güncellendi."));}
    [HttpPost("{id:guid}/post"),Authorize(Policy=AuthorizationPolicies.CanRecordCollections),Idempotent]public async Task<IActionResult>Post(Guid id,CollectionPostRequest? request,CancellationToken ct){request??=new(null,null);await using var tx=await db.Database.BeginTransactionAsync(ct);var x=await db.CustomerCollections.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND"));if(x.Status!="Draft")return Conflict(ApiResponse<object>.Fail("Tahsilat daha önce kaydedilmiş.","ALREADY_POSTED"));FinancialAccount? account=null;if(x.PaymentMethod is "Cash" or "BankTransfer" or "CreditCard"||(x.PaymentMethod=="Other"&&request.FinancialAccountId.HasValue)){if(!request.FinancialAccountId.HasValue)return BadRequest(ApiResponse<object>.Fail(x.PaymentMethod=="Cash"?"Nakit tahsilat için kasa hesabı seçilmelidir.":"Banka havalesi için banka hesabı seçilmelidir.","ACCOUNT_REQUIRED"));account=await db.FinancialAccounts.FirstOrDefaultAsync(a=>a.Id==request.FinancialAccountId,ct);if(account is null)return NotFound(ApiResponse<object>.Fail("Finans hesabı bulunamadı.","ACCOUNT_NOT_FOUND"));if(!account.IsActive)return Conflict(ApiResponse<object>.Fail("Finans hesabı aktif değil.","ACCOUNT_INACTIVE"));if(account.Currency!=x.Currency)return Conflict(ApiResponse<object>.Fail("Finans hesabının para birimi tahsilat ile eşleşmiyor.","CURRENCY_MISMATCH"));if(x.PaymentMethod=="Cash"&&account.AccountType!="Cash")return Conflict(ApiResponse<object>.Fail("Nakit tahsilat için kasa hesabı seçilmelidir.","ACCOUNT_TYPE"));if(x.PaymentMethod=="BankTransfer"&&account.AccountType!="Bank")return Conflict(ApiResponse<object>.Fail("Banka havalesi için banka hesabı seçilmelidir.","ACCOUNT_TYPE"));if(x.PaymentMethod=="CreditCard"&&account.AccountType is not("CreditCardClearing" or "Bank"))return Conflict(ApiResponse<object>.Fail("Kredi kartı tahsilatı için POS veya banka hesabı seçilmelidir.","ACCOUNT_TYPE"));}
        x.Status="Posted";db.CustomerLedgerEntries.Add(new CustomerLedgerEntry{Id=Guid.NewGuid(),EntryNumber=await CustomerFinanceSupport.NextNumber(db,"LED",x.CollectionDate,ct),CustomerId=x.CustomerId,TransactionDate=x.CollectionDate,EntryType="Credit",SourceType="Collection",SourceId=x.Id,ReferenceNumber=x.CollectionNumber,Currency=x.Currency,CreditAmount=x.Amount,Description="Müşteri tahsilatı",Created=DateTime.UtcNow});
        if(account is not null){var ft=await CreateFinance(x,account,"Inflow","CustomerCollection","CustomerCollection",x.Id,ct);x.FinancialAccountId=account.Id;x.FinancialTransactionId=ft.Id;x.FinancePostingStatus="Posted";}
        else if(x.PaymentMethod=="Cheque"){if(request.Cheque is null)return BadRequest(ApiResponse<object>.Fail("Çek tahsilatında çek bilgileri zorunludur.","CHEQUE_REQUIRED"));var c=request.Cheque;if(c.Amount!=x.Amount||c.Currency.ToUpper()!=x.Currency)return Conflict(ApiResponse<object>.Fail("Çek tutarı ve para birimi tahsilat ile eşleşmelidir.","CHEQUE_MISMATCH"));await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(81312)",ct);var prefix=$"CHQ-{x.CollectionDate:yyyyMMdd}-";var vals=await db.CustomerCheques.Where(q=>q.PortfolioNumber.StartsWith(prefix)).Select(q=>q.PortfolioNumber).ToListAsync(ct);var next=vals.Select(v=>int.TryParse(v[prefix.Length..],out var n)?n:0).DefaultIfEmpty().Max()+1;var cheque=new CustomerCheque{Id=Guid.NewGuid(),PortfolioNumber=$"{prefix}{next:0000}",ChequeNumber=c.ChequeNumber,CustomerId=x.CustomerId,CustomerCollectionId=x.Id,BankName=c.BankName,AccountHolder=c.AccountHolder,DrawerName=c.DrawerName,ChequeDate=c.ChequeDate.ToUniversalTime(),DueDate=c.DueDate.ToUniversalTime(),Currency=x.Currency,Amount=x.Amount,Status="InPortfolio",ReceivedDate=x.CollectionDate,Notes=c.Notes};db.CustomerCheques.Add(cheque);db.ChequeEvents.Add(new ChequeEvent{Id=Guid.NewGuid(),CustomerChequeId=cheque.Id,EventType="Received",EventDate=DateTime.UtcNow,PreviousStatus="Draft",NewStatus="InPortfolio",Created=DateTime.UtcNow});x.CustomerChequeId=cheque.Id;x.FinancePostingStatus="Posted";CustomerFinanceSupport.Audit(db,this,"Customer Cheque Received",cheque.Id,c);}
        else{x.FinancePostingStatus=x.PaymentMethod=="Other"?"Pending":"NotRequired";x.FinancePostingWarning=x.PaymentMethod=="Other"?"Finans hesabına aktarılmamış tahsilat.":null;}
        CustomerFinanceSupport.Audit(db,this,"Customer Collection Posted",x.Id,new{x.Amount,x.Currency,x.PaymentMethod,x.FinancePostingStatus});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status,x.FinancePostingStatus,x.FinancePostingWarning},"Tahsilat kaydedildi."));}
    [HttpPost("{id:guid}/allocate"),Authorize(Policy=AuthorizationPolicies.CanAllocateCollections),Idempotent]public Task<IActionResult>Allocate(Guid id,AllocationRequest r,CancellationToken ct)=>AllocateCore(id,r.Lines,"Customer Collection Allocated",ct);
    [HttpPost("{id:guid}/auto-allocate"),Authorize(Policy=AuthorizationPolicies.CanAllocateCollections),Idempotent]public async Task<IActionResult>AutoAllocate(Guid id,CancellationToken ct){var x=await db.CustomerCollections.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND"));var remaining=x.UnallocatedAmount;var recs=await db.CustomerReceivables.AsNoTracking().Where(r=>r.CustomerId==x.CustomerId&&r.Currency==x.Currency&&!r.IsCancelled&&r.OutstandingAmount>0).OrderByDescending(r=>r.DueDate<DateTime.UtcNow.Date).ThenBy(r=>r.DueDate).ThenBy(r=>r.TransactionDate).ThenBy(r=>r.ReceivableNumber).ToListAsync(ct);var lines=new List<AllocationLineRequest>();foreach(var rec in recs){if(remaining<=0)break;var amount=Math.Min(remaining,rec.OutstandingAmount);lines.Add(new(rec.Id,amount,"Otomatik FIFO dağıtım"));remaining-=amount;}return await AllocateCore(id,lines,"Customer Collection Auto Allocated",ct);}
    [HttpGet("{id:guid}/allocation-suggestion")]public async Task<IActionResult>Suggestion(Guid id,CancellationToken ct){var x=await db.CustomerCollections.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();var remaining=x.UnallocatedAmount;var recs=await db.CustomerReceivables.AsNoTracking().Where(r=>r.CustomerId==x.CustomerId&&r.Currency==x.Currency&&!r.IsCancelled&&r.OutstandingAmount>0).OrderByDescending(r=>r.DueDate<DateTime.UtcNow.Date).ThenBy(r=>r.DueDate).ThenBy(r=>r.TransactionDate).ThenBy(r=>r.ReceivableNumber).ToListAsync(ct);var rows=new List<object>();foreach(var rec in recs){if(remaining<=0)break;var amount=Math.Min(remaining,rec.OutstandingAmount);rows.Add(new{rec.Id,rec.ReceivableNumber,rec.DueDate,rec.OutstandingAmount,SuggestedAmount=amount});remaining-=amount;}return Ok(ApiResponse<object>.SuccessResponse(new{Lines=rows,Remaining=remaining}));}
    [HttpPost("{id:guid}/reverse"),Authorize(Policy=AuthorizationPolicies.CanReverseCollections),Idempotent]public async Task<IActionResult>Reverse(Guid id,CancelFinanceRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("Geri alma gerekçesi zorunludur.","VALIDATION_ERROR"));await using var tx=await db.Database.BeginTransactionAsync(ct);var x=await db.CustomerCollections.Include(x=>x.Allocations).ThenInclude(x=>x.CustomerReceivable).FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND"));if(x.IsReversed)return Conflict(ApiResponse<object>.Fail("Bu tahsilat daha önce geri alınmış.","ALREADY_REVERSED"));if(x.Status is "Draft" or "Cancelled")return Conflict(ApiResponse<object>.Fail("Bu tahsilat geri alınamaz.","INVALID_STATUS"));if(x.CustomerChequeId.HasValue){var cheque=await db.CustomerCheques.FirstOrDefaultAsync(q=>q.Id==x.CustomerChequeId,ct);if(cheque?.Status=="DepositedToBank")return Conflict(ApiResponse<object>.Fail("Bu çek bankaya verildiği için doğrudan iptal edilemez.","CHEQUE_DEPOSITED"));if(cheque?.Status=="Collected")return Conflict(ApiResponse<object>.Fail("Önce çek tahsilatı geri alınmalıdır.","CHEQUE_COLLECTED"));if(cheque is not null){var previous=cheque.Status;cheque.Status="Reversed";cheque.IsReversed=true;cheque.ReversedAt=DateTime.UtcNow;cheque.ReversalReason=r.Reason;db.ChequeEvents.Add(new ChequeEvent{Id=Guid.NewGuid(),CustomerChequeId=cheque.Id,EventType="Reversed",EventDate=DateTime.UtcNow,PreviousStatus=previous,NewStatus="Reversed",Reason=r.Reason,Created=DateTime.UtcNow});}}
        if(x.FinancialTransactionId.HasValue){var original=await db.FinancialTransactions.Include(t=>t.FinancialAccount).FirstOrDefaultAsync(t=>t.Id==x.FinancialTransactionId,ct);if(original is not null&&!original.IsReversed){var reverse=await CreateFinance(x,original.FinancialAccount,"Outflow","Reversal","Reversal",original.Id,ct);original.IsReversed=true;original.ReversalTransactionId=reverse.Id;original.ReversedAt=DateTime.UtcNow;original.ReversalReason=r.Reason;}}
        foreach(var a in x.Allocations.Where(a=>!a.IsReversed)){a.IsReversed=true;a.ReversedAt=DateTime.UtcNow;var rec=a.CustomerReceivable;rec.AllocatedAmount-=a.AllocatedAmount;rec.OutstandingAmount+=a.AllocatedAmount;rec.Status=CustomerFinanceSupport.Status(rec);}x.IsReversed=true;x.Status="Reversed";x.FinancePostingStatus="Reversed";x.ReversedAt=DateTime.UtcNow;x.ReversedBy=User.Identity?.Name;x.ReversalReason=r.Reason;x.UnallocatedAmount=0;db.CustomerLedgerEntries.Add(new CustomerLedgerEntry{Id=Guid.NewGuid(),EntryNumber=await CustomerFinanceSupport.NextNumber(db,"LED",DateTime.UtcNow,ct),CustomerId=x.CustomerId,TransactionDate=DateTime.UtcNow,EntryType="Debit",SourceType="Reversal",SourceId=x.Id,ReferenceNumber=x.CollectionNumber,Currency=x.Currency,DebitAmount=x.Amount,Description=r.Reason,Created=DateTime.UtcNow});CustomerFinanceSupport.Audit(db,this,"Customer Collection Reversed",x.Id,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status,x.FinancePostingStatus},"Tahsilat geri alındı."));}
    [HttpPost("{id:guid}/cancel"),Authorize(Policy=AuthorizationPolicies.CanRecordCollections),Idempotent]public async Task<IActionResult>Cancel(Guid id,CancelFinanceRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("İptal gerekçesi zorunludur.","VALIDATION_ERROR"));var x=await db.CustomerCollections.FindAsync([id],ct);if(x is null)return NotFound();if(x.Status!="Draft")return Conflict(ApiResponse<object>.Fail("Yalnız taslak tahsilat iptal edilebilir.","INVALID_STATUS"));x.Status="Cancelled";x.Notes=$"{x.Notes}\nİptal: {r.Reason}";CustomerFinanceSupport.Audit(db,this,"Customer Collection Cancelled",x.Id,r);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status}));}
    [HttpGet("summary")]public async Task<IActionResult>Summary(CancellationToken ct){var rows=await db.CustomerCollections.AsNoTracking().Where(x=>x.Status!="Draft"&&x.Status!="Cancelled"&&!x.IsReversed).GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,TotalCollected=g.Sum(x=>x.Amount),UnallocatedCollection=g.Sum(x=>x.UnallocatedAmount),Today=g.Where(x=>x.CollectionDate.Date==DateTime.UtcNow.Date).Sum(x=>x.Amount),ThisMonth=g.Where(x=>x.CollectionDate.Year==DateTime.UtcNow.Year&&x.CollectionDate.Month==DateTime.UtcNow.Month).Sum(x=>x.Amount)}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("export.csv"),Authorize(Policy=AuthorizationPolicies.CanExportCustomerStatement)]public async Task<IActionResult>Export(CancellationToken ct){var rows=await db.CustomerCollections.AsNoTracking().OrderByDescending(x=>x.CollectionDate).Select(x=>new{x.CollectionNumber,CustomerName=x.Customer.CompanyName??x.Customer.Name,x.CollectionDate,x.Amount,x.UnallocatedAmount,x.Currency,x.PaymentMethod,x.ReferenceNumber,x.Status}).ToListAsync(ct);var sb=new StringBuilder("\uFEFFTahsilat No;Müşteri;Tarih;Tutar;Dağıtılmamış;Para Birimi;Yöntem;Referans;Durum\n");foreach(var x in rows)sb.AppendLine($"{x.CollectionNumber};{x.CustomerName?.Replace(';',',')};{x.CollectionDate:dd.MM.yyyy};{x.Amount};{x.UnallocatedAmount};{x.Currency};{x.PaymentMethod};{x.ReferenceNumber};{x.Status}");CustomerFinanceSupport.Audit(db,this,"Customer Collections Exported",Guid.Empty,new{});await db.SaveChangesAsync(ct);return File(Encoding.UTF8.GetBytes(sb.ToString()),"text/csv; charset=utf-8",$"tahsilatlar-{DateTime.UtcNow:yyyyMMdd}.csv");}
    private async Task<IActionResult>AllocateCore(Guid id,IReadOnlyList<AllocationLineRequest> lines,string audit,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var x=await db.CustomerCollections.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Tahsilat bulunamadı.","COLLECTION_NOT_FOUND"));if(x.Status is not("Posted" or "PartiallyAllocated"))return Conflict(ApiResponse<object>.Fail("Tahsilat kaydedilmeden dağıtım yapılamaz.","NOT_POSTED"));if(lines.Count==0)return BadRequest(ApiResponse<object>.Fail("Dağıtım satırı zorunludur.","VALIDATION_ERROR"));var sum=lines.Sum(l=>l.Amount);if(sum>x.UnallocatedAmount)return Conflict(ApiResponse<object>.Fail("Dağıtım tutarı tahsilatın kalan miktarını aşıyor.","COLLECTION_EXCEEDED"));foreach(var line in lines){if(line.Amount<=0)return BadRequest(ApiResponse<object>.Fail("Dağıtım tutarı sıfırdan büyük olmalıdır.","VALIDATION_ERROR"));var rec=await db.CustomerReceivables.FirstOrDefaultAsync(r=>r.Id==line.ReceivableId,ct);if(rec is null)return NotFound(ApiResponse<object>.Fail("Alacak bulunamadı.","RECEIVABLE_NOT_FOUND"));if(rec.CustomerId!=x.CustomerId)return Conflict(ApiResponse<object>.Fail("Tahsilat ve alacak aynı müşteriye ait olmalıdır.","CUSTOMER_MISMATCH"));if(rec.Currency!=x.Currency)return Conflict(ApiResponse<object>.Fail("Tahsilat ve alacak para birimleri eşleşmiyor.","CURRENCY_MISMATCH"));if(line.Amount>rec.OutstandingAmount)return Conflict(ApiResponse<object>.Fail("Dağıtım tutarı alacağın açık miktarını aşıyor.","RECEIVABLE_EXCEEDED"));db.CollectionAllocations.Add(new CollectionAllocation{Id=Guid.NewGuid(),CustomerCollectionId=x.Id,CustomerReceivableId=rec.Id,OrderId=rec.OrderId,AllocatedAmount=line.Amount,Currency=x.Currency,AllocationDate=DateTime.UtcNow,Notes=line.Notes,Created=DateTime.UtcNow});rec.AllocatedAmount+=line.Amount;rec.OutstandingAmount-=line.Amount;rec.Status=CustomerFinanceSupport.Status(rec);x.UnallocatedAmount-=line.Amount;}x.Status=x.UnallocatedAmount==0?"FullyAllocated":"PartiallyAllocated";CustomerFinanceSupport.Audit(db,this,audit,x.Id,new{Lines=lines});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status,x.UnallocatedAmount}));}
    private async Task<string?>Validate(CollectionRequest r,CancellationToken ct){if(!await db.Customers.AnyAsync(x=>x.Id==r.CustomerId&&x.IsActive,ct))return "Müşteri bulunamadı.";if(r.Amount<=0)return "Tahsilat tutarı sıfırdan büyük olmalıdır.";if(string.IsNullOrWhiteSpace(r.Currency))return "Para birimi zorunludur.";if(!Methods.Contains(r.PaymentMethod))return "Desteklenmeyen ödeme yöntemi.";return null;}
    private async Task<FinancialTransaction>CreateFinance(CustomerCollection collection,FinancialAccount account,string direction,string type,string sourceType,Guid sourceId,CancellationToken ct){await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(81311)",ct);var prefix=$"FTX-{DateTime.UtcNow:yyyyMMdd}-";var vals=await db.FinancialTransactions.Where(t=>t.TransactionNumber.StartsWith(prefix)).Select(t=>t.TransactionNumber).ToListAsync(ct);var next=vals.Select(v=>int.TryParse(v[prefix.Length..],out var n)?n:0).DefaultIfEmpty().Max()+1;var ft=new FinancialTransaction{Id=Guid.NewGuid(),TransactionNumber=$"{prefix}{next:0000}",FinancialAccountId=account.Id,TransactionDate=DateTime.UtcNow,TransactionType=type,Direction=direction,SourceType=sourceType,SourceId=sourceId,CustomerId=collection.CustomerId,CustomerCollectionId=collection.Id,Currency=collection.Currency,Amount=collection.Amount,Description=$"{collection.CollectionNumber} tahsilatı",ReferenceNumber=collection.ReferenceNumber,BankReference=collection.BankReference,Created=DateTime.UtcNow};db.FinancialTransactions.Add(ft);return ft;}
}
public record CollectionRequest(Guid CustomerId,DateTime CollectionDate,string Currency,decimal Amount,string PaymentMethod,string? ReferenceNumber,string? BankReference,string? Notes);
public record AllocationRequest(List<AllocationLineRequest> Lines);
public record AllocationLineRequest(Guid ReceivableId,decimal Amount,string? Notes);
public record CollectionPostRequest(Guid? FinancialAccountId,ChequePostRequest? Cheque);
public record ChequePostRequest(string ChequeNumber,string BankName,string AccountHolder,string DrawerName,DateTime ChequeDate,DateTime DueDate,string Currency,decimal Amount,string? Notes);
