using System.Text;
using Asp.Versioning;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Domain.Enums;
using Fixar.Infrastructure.Identity;
using Fixar.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fixar.API.Controllers;

[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/customer-ledger"),Authorize(Policy=AuthorizationPolicies.CanViewCustomerLedger)]
public class CustomerLedgerController(ApplicationDbContext db):ControllerBase
{
    [HttpGet("customer/{customerId:guid}")]public async Task<IActionResult>Entries(Guid customerId,DateTime? dateFrom,DateTime? dateTo,string? currency,string? entryType,string? sourceType,string? search,CancellationToken ct){var q=Filter(customerId,dateFrom,dateTo,currency,entryType,sourceType,search);var rows=await q.OrderBy(x=>x.TransactionDate).ThenBy(x=>x.Created).Select(x=>new CustomerLedgerEntryDto(x.Id,x.EntryNumber,x.TransactionDate,x.DueDate,x.EntryType,x.SourceType,x.SourceId,x.ReferenceNumber,x.Currency,x.DebitAmount,x.CreditAmount,x.Description,x.IsReversed)).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("customer/{customerId:guid}/balance")]public async Task<IActionResult>Balance(Guid customerId,CancellationToken ct){var ledger=await db.CustomerLedgerEntries.AsNoTracking().Where(x=>x.CustomerId==customerId).GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,TotalReceivable=g.Sum(x=>x.DebitAmount),TotalCollected=g.Sum(x=>x.CreditAmount),OutstandingBalance=g.Sum(x=>x.DebitAmount-x.CreditAmount)}).ToListAsync(ct);var allocated=await db.CustomerReceivables.AsNoTracking().Where(x=>x.CustomerId==customerId&&!x.IsCancelled).GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,TotalAllocated=g.Sum(x=>x.AllocatedAmount),OverdueBalance=g.Where(x=>x.OutstandingAmount>0&&x.DueDate<DateTime.UtcNow.Date).Sum(x=>x.OutstandingAmount),OpenReceivableCount=g.Count(x=>x.OutstandingAmount>0),OverdueReceivableCount=g.Count(x=>x.OutstandingAmount>0&&x.DueDate<DateTime.UtcNow.Date)}).ToListAsync(ct);var unallocated=await db.CustomerCollections.AsNoTracking().Where(x=>x.CustomerId==customerId&&!x.IsReversed&&x.Status!="Draft"&&x.Status!="Cancelled").GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,Amount=g.Sum(x=>x.UnallocatedAmount)}).ToListAsync(ct);var rows=ledger.Select(x=>new CustomerBalanceDto(x.Currency,x.TotalReceivable,x.TotalCollected,allocated.FirstOrDefault(a=>a.Currency==x.Currency)?.TotalAllocated??0,unallocated.FirstOrDefault(a=>a.Currency==x.Currency)?.Amount??0,x.OutstandingBalance,allocated.FirstOrDefault(a=>a.Currency==x.Currency)?.OverdueBalance??0,allocated.FirstOrDefault(a=>a.Currency==x.Currency)?.OpenReceivableCount??0,allocated.FirstOrDefault(a=>a.Currency==x.Currency)?.OverdueReceivableCount??0));return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("customer/{customerId:guid}/statement")]public async Task<IActionResult>Statement(Guid customerId,DateTime? dateFrom,DateTime? dateTo,string? currency,CancellationToken ct){var entries=await Filter(customerId,dateFrom,dateTo,currency,null,null,null).OrderBy(x=>x.TransactionDate).ThenBy(x=>x.Created).ToListAsync(ct);decimal balance=0;var rows=entries.Select(x=>{balance+=x.DebitAmount-x.CreditAmount;return new{x.Id,x.EntryNumber,x.TransactionDate,x.DueDate,x.EntryType,x.SourceType,x.ReferenceNumber,x.Currency,x.DebitAmount,x.CreditAmount,RunningBalance=balance,x.Description};}).ToList();return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("aging")]public async Task<IActionResult>Aging(Guid? customerId,CancellationToken ct){var today=DateTime.UtcNow.Date;var q=db.CustomerReceivables.AsNoTracking().Where(x=>!x.IsCancelled&&x.OutstandingAmount>0);if(customerId.HasValue)q=q.Where(x=>x.CustomerId==customerId);var raw=await q.Select(x=>new AgingRaw(x.CustomerId,x.Customer.CustomerCode,x.Customer.CompanyName??x.Customer.Name,x.Currency,x.DueDate,x.OutstandingAmount,x.ReceivableNumber)).ToListAsync(ct);var rows=raw.GroupBy(x=>new{x.CustomerId,x.CustomerCode,x.CustomerName,x.Currency}).Select(g=>new ReceivableAgingDto(g.Key.CustomerId,g.Key.CustomerCode,g.Key.CustomerName,g.Key.Currency,g.Where(x=>x.DueDate>=today).Sum(x=>x.OutstandingAmount),Bucket(g,1,30,today),Bucket(g,31,60,today),Bucket(g,61,90,today),Bucket(g,91,180,today),g.Where(x=>(today-x.DueDate.Date).Days>=181).Sum(x=>x.OutstandingAmount),g.Count(),g.Min(x=>x.DueDate),g.Max(x=>x.OutstandingAmount),g.Sum(x=>x.OutstandingAmount))).ToList();return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("summary")]public async Task<IActionResult>Summary(CancellationToken ct){var rows=await db.CustomerLedgerEntries.AsNoTracking().GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,Debit=g.Sum(x=>x.DebitAmount),Credit=g.Sum(x=>x.CreditAmount),Balance=g.Sum(x=>x.DebitAmount-x.CreditAmount)}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("customer/{customerId:guid}/statement.csv"),Authorize(Policy=AuthorizationPolicies.CanExportCustomerStatement)]public async Task<IActionResult>Export(Guid customerId,DateTime? dateFrom,DateTime? dateTo,string? currency,CancellationToken ct){var entries=await Filter(customerId,dateFrom,dateTo,currency,null,null,null).OrderBy(x=>x.TransactionDate).ToListAsync(ct);var sb=new StringBuilder("\uFEFFTarih;Belge No;Kaynak;Açıklama;Vade;Borç;Alacak;Para Birimi\n");foreach(var x in entries)sb.AppendLine($"{x.TransactionDate:dd.MM.yyyy};{x.ReferenceNumber};{x.SourceType};{x.Description?.Replace(';',',')};{x.DueDate:dd.MM.yyyy};{x.DebitAmount};{x.CreditAmount};{x.Currency}");db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),UserName=User.Identity?.Name??"system",Action=AuditAction.Create,EntityName="Customer Statement Exported",EntityId=customerId.ToString(),Timestamp=DateTime.UtcNow,IpAddress=HttpContext.Connection.RemoteIpAddress?.ToString()});await db.SaveChangesAsync(ct);return File(Encoding.UTF8.GetBytes(sb.ToString()),"text/csv; charset=utf-8",$"musteri-ekstresi-{DateTime.UtcNow:yyyyMMdd}.csv");}
    private IQueryable<CustomerLedgerEntry>Filter(Guid customerId,DateTime? from,DateTime? to,string? currency,string? entryType,string? sourceType,string? search){var q=db.CustomerLedgerEntries.AsNoTracking().Where(x=>x.CustomerId==customerId);if(from.HasValue)q=q.Where(x=>x.TransactionDate>=from);if(to.HasValue)q=q.Where(x=>x.TransactionDate<=to);if(!string.IsNullOrWhiteSpace(currency))q=q.Where(x=>x.Currency==currency.ToUpper());if(!string.IsNullOrWhiteSpace(entryType))q=q.Where(x=>x.EntryType==entryType);if(!string.IsNullOrWhiteSpace(sourceType))q=q.Where(x=>x.SourceType==sourceType);if(!string.IsNullOrWhiteSpace(search)){var s=search.ToLower();q=q.Where(x=>x.ReferenceNumber.ToLower().Contains(s)||(x.Description!=null&&x.Description.ToLower().Contains(s)));}return q;}
    private static decimal Bucket(IEnumerable<AgingRaw> rows,int min,int max,DateTime today)=>rows.Where(x=>(today-x.DueDate.Date).Days>=min&&(today-x.DueDate.Date).Days<=max).Sum(x=>x.OutstandingAmount);
}
public record AgingRaw(Guid CustomerId,string CustomerCode,string CustomerName,string Currency,DateTime DueDate,decimal OutstandingAmount,string ReceivableNumber);
public record CustomerLedgerEntryDto(Guid Id,string EntryNumber,DateTime TransactionDate,DateTime? DueDate,string EntryType,string SourceType,Guid SourceId,string ReferenceNumber,string Currency,decimal DebitAmount,decimal CreditAmount,string? Description,bool IsReversed);
public record CustomerBalanceDto(string Currency,decimal TotalReceivable,decimal TotalCollected,decimal TotalAllocated,decimal UnallocatedCollection,decimal OutstandingBalance,decimal OverdueBalance,int OpenReceivableCount,int OverdueReceivableCount);
public record ReceivableAgingDto(Guid CustomerId,string CustomerCode,string CustomerName,string Currency,decimal NotDue,decimal Days1To30,decimal Days31To60,decimal Days61To90,decimal Days91To180,decimal Days181Plus,int ReceivableCount,DateTime OldestDueDate,decimal LargestOverdueReceivable,decimal TotalOutstanding);
