using Asp.Versioning;
using Fixar.API.Security;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Infrastructure.Identity;
using Fixar.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace Fixar.API.Controllers;

[ApiController, ApiVersion("1.0"), Route("api/v{version:apiVersion}/customer-receivables"), Authorize(Policy = AuthorizationPolicies.CanViewCustomerFinance)]
public class CustomerReceivablesController(ApplicationDbContext db) : ControllerBase
{
    [HttpGet("customer-lookup")]public async Task<IActionResult>CustomerLookup(CancellationToken ct){var rows=await db.Customers.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.CustomerCode).Select(x=>new{x.Id,x.CustomerCode,x.Name,x.CompanyName,x.DefaultCurrency}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet]
    public async Task<IActionResult> List(Guid? customerId, Guid? orderId, string? status, string? currency, DateTime? dueFrom, DateTime? dueTo, bool overdueOnly, DateTime? dateFrom, DateTime? dateTo, string? search, CancellationToken ct)
    {
        var q = db.CustomerReceivables.AsNoTracking().AsQueryable();
        if (customerId.HasValue) q = q.Where(x => x.CustomerId == customerId); if (orderId.HasValue) q = q.Where(x => x.OrderId == orderId);
        if (!string.IsNullOrWhiteSpace(status)) q = q.Where(x => x.Status == status); if (!string.IsNullOrWhiteSpace(currency)) q = q.Where(x => x.Currency == currency.ToUpper());
        if (dueFrom.HasValue) q = q.Where(x => x.DueDate >= dueFrom); if (dueTo.HasValue) q = q.Where(x => x.DueDate <= dueTo); if (overdueOnly) q = q.Where(x => x.OutstandingAmount > 0 && x.DueDate < DateTime.UtcNow.Date);
        if (dateFrom.HasValue) q = q.Where(x => x.TransactionDate >= dateFrom); if (dateTo.HasValue) q = q.Where(x => x.TransactionDate <= dateTo);
        if (!string.IsNullOrWhiteSpace(search)) { var s = search.ToLower(); q = q.Where(x => x.ReceivableNumber.ToLower().Contains(s) || (x.OrderNumberSnapshot != null && x.OrderNumberSnapshot.ToLower().Contains(s)) || x.Customer.Name.ToLower().Contains(s)); }
        var rows = await q.OrderBy(x => x.DueDate).Select(x => new CustomerReceivableListDto(x.Id, x.ReceivableNumber, x.CustomerId, x.Customer.CustomerCode, x.Customer.CompanyName ?? x.Customer.Name, x.OrderId, x.OrderNumberSnapshot, x.TransactionDate, x.DueDate, x.Currency, x.OriginalAmount, x.AllocatedAmount, x.OutstandingAmount, x.Status, x.SourceType, x.IsCancelled, x.OutstandingAmount > 0 && x.DueDate < DateTime.UtcNow.Date ? (DateTime.UtcNow.Date - x.DueDate.Date).Days : 0)).ToListAsync(ct);
        return Ok(ApiResponse<object>.SuccessResponse(rows));
    }

    [HttpGet("{id:guid}")] public async Task<IActionResult> Detail(Guid id, CancellationToken ct) { var x = await db.CustomerReceivables.AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id,x.ReceivableNumber,x.CustomerId,CustomerName=x.Customer.CompanyName??x.Customer.Name,x.OrderId,x.OrderNumberSnapshot,x.TransactionDate,x.DueDate,x.Currency,x.OriginalAmount,x.AllocatedAmount,x.OutstandingAmount,x.Status,x.SourceType,x.Description,x.IsActive,x.IsCancelled,x.CancellationReason,x.CancelledAt,Allocations=x.Allocations.Select(a=>new CollectionAllocationDto(a.Id,a.CustomerCollectionId,a.CustomerCollection.CollectionNumber,a.CustomerReceivableId,a.AllocatedAmount,a.Currency,a.AllocationDate,a.Notes,a.IsReversed)) }).FirstOrDefaultAsync(ct); return x is null ? NotFound(ApiResponse<object>.Fail("Alacak bulunamadı.","RECEIVABLE_NOT_FOUND")) : Ok(ApiResponse<object>.SuccessResponse(x)); }
    [HttpGet("customer/{customerId:guid}")] public Task<IActionResult> Customer(Guid customerId, CancellationToken ct) => List(customerId,null,null,null,null,null,false,null,null,null,ct);

    [HttpPost, Authorize(Policy = AuthorizationPolicies.CanManageReceivables), Idempotent]
    public async Task<IActionResult> Create(CreateReceivableRequest r, CancellationToken ct)
    {
        if (r.Amount <= 0) return BadRequest(ApiResponse<object>.Fail("Alacak tutarı sıfırdan büyük olmalıdır.","VALIDATION_ERROR"));
        var customer = await db.Customers.FindAsync([r.CustomerId],ct); if(customer is null)return NotFound(ApiResponse<object>.Fail("Müşteri bulunamadı.","CUSTOMER_NOT_FOUND"));
        await using var tx=await db.Database.BeginTransactionAsync(ct); var x=await CustomerFinanceSupport.CreateReceivable(db,customer,null,r.Amount,r.Currency,r.TransactionDate.ToUniversalTime(),r.DueDate.ToUniversalTime(),"ManualDebit",r.Description,ct); CustomerFinanceSupport.Audit(db,this,"Customer Receivable Created",x.Id,r); await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.ReceivableNumber},"Alacak oluşturuldu."));
    }

    [HttpPost("{id:guid}/cancel"), Authorize(Policy = AuthorizationPolicies.CanManageReceivables), Idempotent]
    public async Task<IActionResult> Cancel(Guid id, CancelFinanceRequest r, CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("İptal gerekçesi zorunludur.","VALIDATION_ERROR"));var x=await db.CustomerReceivables.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Alacak bulunamadı.","RECEIVABLE_NOT_FOUND"));if(x.AllocatedAmount>0)return Conflict(ApiResponse<object>.Fail("Kısmi tahsilatı bulunan sipariş alacağı doğrudan iptal edilemez.","HAS_ALLOCATIONS"));if(x.IsCancelled)return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status},"Alacak zaten iptal edilmiş."));await using var tx=await db.Database.BeginTransactionAsync(ct);x.IsCancelled=true;x.IsActive=false;x.Status="Cancelled";x.CancellationReason=r.Reason;x.CancelledAt=DateTime.UtcNow;x.CancelledBy=User.Identity?.Name;db.CustomerLedgerEntries.Add(new CustomerLedgerEntry{Id=Guid.NewGuid(),EntryNumber=await CustomerFinanceSupport.NextNumber(db,"LED",DateTime.UtcNow,ct),CustomerId=x.CustomerId,TransactionDate=DateTime.UtcNow,EntryType="Credit",SourceType="Adjustment",SourceId=x.Id,ReferenceNumber=x.ReceivableNumber,Currency=x.Currency,CreditAmount=x.OutstandingAmount,Description="Alacak iptali",Created=DateTime.UtcNow});CustomerFinanceSupport.Audit(db,this,"Customer Receivable Cancelled",x.Id,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status},"Alacak iptal edildi."));}
    [HttpPost("{id:guid}/recalculate-status")] public async Task<IActionResult> Recalculate(Guid id,CancellationToken ct){var x=await db.CustomerReceivables.FindAsync([id],ct);if(x is null)return NotFound();x.Status=CustomerFinanceSupport.Status(x);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status}));}
    [HttpGet("summary")] public async Task<IActionResult> Summary(CancellationToken ct){var rows=await db.CustomerReceivables.AsNoTracking().Where(x=>!x.IsCancelled).GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,TotalReceivable=g.Sum(x=>x.OriginalAmount),TotalAllocated=g.Sum(x=>x.AllocatedAmount),OutstandingBalance=g.Sum(x=>x.OutstandingAmount),OverdueBalance=g.Where(x=>x.OutstandingAmount>0&&x.DueDate<DateTime.UtcNow.Date).Sum(x=>x.OutstandingAmount),OpenReceivableCount=g.Count(x=>x.OutstandingAmount>0),OverdueReceivableCount=g.Count(x=>x.OutstandingAmount>0&&x.DueDate<DateTime.UtcNow.Date)}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpGet("export.csv"),Authorize(Policy=AuthorizationPolicies.CanExportCustomerStatement)]public async Task<IActionResult>Export(bool overdueOnly,CancellationToken ct){var q=db.CustomerReceivables.AsNoTracking().Where(x=>!x.IsCancelled&&x.OutstandingAmount>0);if(overdueOnly)q=q.Where(x=>x.DueDate<DateTime.UtcNow.Date);var rows=await q.OrderBy(x=>x.DueDate).Select(x=>new{x.ReceivableNumber,CustomerName=x.Customer.CompanyName??x.Customer.Name,x.OrderNumberSnapshot,x.TransactionDate,x.DueDate,x.OriginalAmount,x.AllocatedAmount,x.OutstandingAmount,x.Currency,x.Status}).ToListAsync(ct);var sb=new StringBuilder("\uFEFFAlacak No;Müşteri;Sipariş;İşlem Tarihi;Vade;Orijinal Tutar;Tahsil Edilen;Kalan;Para Birimi;Durum\n");foreach(var x in rows)sb.AppendLine($"{x.ReceivableNumber};{x.CustomerName?.Replace(';',',')};{x.OrderNumberSnapshot};{x.TransactionDate:dd.MM.yyyy};{x.DueDate:dd.MM.yyyy};{x.OriginalAmount};{x.AllocatedAmount};{x.OutstandingAmount};{x.Currency};{x.Status}");CustomerFinanceSupport.Audit(db,this,overdueOnly?"Overdue Receivables Exported":"Open Receivables Exported",Guid.Empty,new{overdueOnly});await db.SaveChangesAsync(ct);return File(Encoding.UTF8.GetBytes(sb.ToString()),"text/csv; charset=utf-8",$"{(overdueOnly?"vadesi-gecen":"acik-alacaklar")}-{DateTime.UtcNow:yyyyMMdd}.csv");}
    [HttpGet("backfill-preview")] public async Task<IActionResult> BackfillPreview(CancellationToken ct){var rows=await db.Orders.AsNoTracking().Where(o=>(o.Status=="Confirmed"||o.Status=="Completed")&&!o.IsCancelled&&!db.CustomerReceivables.Any(r=>r.OrderId==o.Id&&!r.IsCancelled)).Select(o=>new{o.Id,o.OrderNumber,o.CustomerId,CustomerName=o.Customer.CompanyName??o.Customer.Name,o.GrandTotal,o.Currency,DueDate=o.OrderDate.AddDays(o.PaymentTermDays),Warning="Tahsilat geçmişi bilinmiyor; seçilmeden borç oluşturulmaz."}).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
    [HttpPost("backfill"),Authorize(Policy=AuthorizationPolicies.CanManageReceivables),Idempotent] public async Task<IActionResult> Backfill(ReceivableBackfillRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var orders=await db.Orders.Include(x=>x.Customer).Where(x=>r.OrderIds.Contains(x.Id)&&(x.Status=="Confirmed"||x.Status=="Completed")&&!x.IsCancelled).ToListAsync(ct);var created=new List<string>();foreach(var o in orders){if(await db.CustomerReceivables.AnyAsync(x=>x.OrderId==o.Id&&!x.IsCancelled,ct))continue;var due=o.OrderDate.AddDays(o.PaymentTermDays);var rec=await CustomerFinanceSupport.CreateReceivable(db,o.Customer,o,o.GrandTotal,o.Currency,o.OrderDate,due,"SalesOrder","Seçili geçmiş sipariş alacağı",ct);created.Add(rec.ReceivableNumber);}CustomerFinanceSupport.Audit(db,this,"Customer Receivable Backfill",Guid.Empty,new{r.OrderIds,Created=created});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{Created=created.Count,ReceivableNumbers=created}));}
}
public record CustomerReceivableListDto(Guid Id,string ReceivableNumber,Guid CustomerId,string CustomerCode,string CustomerName,Guid? OrderId,string? OrderNumber,DateTime TransactionDate,DateTime DueDate,string Currency,decimal OriginalAmount,decimal AllocatedAmount,decimal OutstandingAmount,string Status,string SourceType,bool IsCancelled,int OverdueDays);
public record CollectionAllocationDto(Guid Id,Guid CollectionId,string CollectionNumber,Guid ReceivableId,decimal AllocatedAmount,string Currency,DateTime AllocationDate,string? Notes,bool IsReversed);
public record CreateReceivableRequest(Guid CustomerId,DateTime TransactionDate,DateTime DueDate,string Currency,decimal Amount,string? Description);
public record CancelFinanceRequest(string Reason);
public record ReceivableBackfillRequest(List<Guid> OrderIds);
