using Asp.Versioning;using Fixar.API.Security;using Fixar.Application.Common.Models;using Fixar.Domain.Entities;using Fixar.Infrastructure.Identity;using Fixar.Infrastructure.Persistence;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace Fixar.API.Controllers;
[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/financial-accounts"),Authorize(Policy=AuthorizationPolicies.CanViewFinancialAccounts)]
public class FinancialAccountsController(ApplicationDbContext db):ControllerBase
{
 static readonly string[] Types=["Cash","Bank","CreditCardClearing","Other"];
 [HttpGet]public async Task<IActionResult>List(string? accountType,string? currency,bool? isActive,string? search,CancellationToken ct){var q=db.FinancialAccounts.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(accountType))q=q.Where(x=>x.AccountType==accountType);if(!string.IsNullOrWhiteSpace(currency))q=q.Where(x=>x.Currency==currency.ToUpper());if(isActive.HasValue)q=q.Where(x=>x.IsActive==isActive);if(!string.IsNullOrWhiteSpace(search)){var s=search.ToLower();q=q.Where(x=>x.AccountCode.ToLower().Contains(s)||x.Name.ToLower().Contains(s)||(x.Iban!=null&&x.Iban.ToLower().Contains(s)));}var rows=await q.OrderBy(x=>x.AccountCode).Select(x=>new FinancialAccountListDto(x.Id,x.AccountCode,x.Name,x.AccountType,x.Currency,x.BankName,x.Iban,x.OpeningBalance,x.OpeningBalance+db.FinancialTransactions.Where(t=>t.FinancialAccountId==x.Id&&!t.IsReversed).Sum(t=>t.Direction=="Inflow"?t.Amount:-t.Amount),db.FinancialTransactions.Where(t=>t.FinancialAccountId==x.Id).Max(t=>(DateTime?)t.TransactionDate),x.IsActive)).ToListAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(rows));}
 [HttpGet("{id:guid}")]public async Task<IActionResult>Detail(Guid id,CancellationToken ct){var x=await db.FinancialAccounts.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.AccountCode,x.Name,x.AccountType,x.Currency,x.BankName,x.BranchName,x.Iban,x.AccountNumber,x.OpeningBalance,x.OpeningBalanceDate,x.IsActive,x.Notes,Balance=x.OpeningBalance+db.FinancialTransactions.Where(t=>t.FinancialAccountId==x.Id&&!t.IsReversed).Sum(t=>t.Direction=="Inflow"?t.Amount:-t.Amount)}).FirstOrDefaultAsync(ct);return x is null?NotFound(ApiResponse<object>.Fail("Finans hesabı bulunamadı.","ACCOUNT_NOT_FOUND")):Ok(ApiResponse<object>.SuccessResponse(x));}
 [HttpGet("{id:guid}/balance")]public async Task<IActionResult>Balance(Guid id,CancellationToken ct){var x=await db.FinancialAccounts.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.AccountCode,x.Currency,x.OpeningBalance,Inflow=db.FinancialTransactions.Where(t=>t.FinancialAccountId==x.Id&&!t.IsReversed&&t.Direction=="Inflow").Sum(t=>(decimal?)t.Amount)??0,Outflow=db.FinancialTransactions.Where(t=>t.FinancialAccountId==x.Id&&!t.IsReversed&&t.Direction=="Outflow").Sum(t=>(decimal?)t.Amount)??0}).FirstOrDefaultAsync(ct);return x is null?NotFound():Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.AccountCode,x.Currency,x.OpeningBalance,x.Inflow,x.Outflow,CurrentBalance=x.OpeningBalance+x.Inflow-x.Outflow}));}
 [HttpGet("{id:guid}/transactions")]public async Task<IActionResult>Transactions(Guid id,CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(await db.FinancialTransactions.AsNoTracking().Where(x=>x.FinancialAccountId==id).OrderByDescending(x=>x.TransactionDate).Select(x=>new{x.Id,x.TransactionNumber,x.TransactionDate,x.Direction,x.TransactionType,x.SourceType,x.Currency,x.Amount,x.Description,x.ReferenceNumber,x.IsReversed}).ToListAsync(ct)));
 [HttpPost,Authorize(Policy=AuthorizationPolicies.CanManageFinancialAccounts),Idempotent]public async Task<IActionResult>Create(FinancialAccountRequest r,CancellationToken ct){var error=await Validate(r,null,ct);if(error!=null)return BadRequest(ApiResponse<object>.Fail(error,"VALIDATION_ERROR"));await using var tx=await db.Database.BeginTransactionAsync(ct);await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(81310)",ct);var prefix=r.AccountType=="Cash"?"CASH":r.AccountType=="Bank"?"BANK":"FIN";var codes=await db.FinancialAccounts.Where(x=>x.AccountCode.StartsWith(prefix+"-")).Select(x=>x.AccountCode).ToListAsync(ct);var next=codes.Select(x=>int.TryParse(x[(prefix.Length+1)..],out var n)?n:0).DefaultIfEmpty().Max()+1;var x=new FinancialAccount{Id=Guid.NewGuid(),AccountCode=$"{prefix}-{next:0000}",Name=r.Name.Trim(),AccountType=r.AccountType,Currency=r.Currency.ToUpper(),BankName=r.BankName,BranchName=r.BranchName,Iban=Clean(r.Iban),AccountNumber=r.AccountNumber,OpeningBalance=r.OpeningBalance,OpeningBalanceDate=r.OpeningBalanceDate.ToUniversalTime(),Notes=r.Notes,IsActive=true};db.FinancialAccounts.Add(x);CustomerFinanceSupport.Audit(db,this,"Financial Account Created",x.Id,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.AccountCode}));}
 [HttpPut("{id:guid}"),Authorize(Policy=AuthorizationPolicies.CanManageFinancialAccounts)]public async Task<IActionResult>Update(Guid id,FinancialAccountRequest r,CancellationToken ct){var x=await db.FinancialAccounts.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Finans hesabı bulunamadı.","ACCOUNT_NOT_FOUND"));if(x.Currency!=r.Currency.ToUpper())return Conflict(ApiResponse<object>.Fail("Hareket gören finans hesabının para birimi değiştirilemez.","CURRENCY_LOCKED"));var error=await Validate(r,id,ct);if(error!=null)return BadRequest(ApiResponse<object>.Fail(error,"VALIDATION_ERROR"));x.Name=r.Name.Trim();x.AccountType=r.AccountType;x.BankName=r.BankName;x.BranchName=r.BranchName;x.Iban=Clean(r.Iban);x.AccountNumber=r.AccountNumber;x.Notes=r.Notes;CustomerFinanceSupport.Audit(db,this,"Financial Account Updated",x.Id,r);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id}));}
 [HttpPost("{id:guid}/activate"),Authorize(Policy=AuthorizationPolicies.CanManageFinancialAccounts),Idempotent]public Task<IActionResult>Activate(Guid id,CancellationToken ct)=>Active(id,true,ct);
 [HttpPost("{id:guid}/deactivate"),Authorize(Policy=AuthorizationPolicies.CanManageFinancialAccounts),Idempotent]public Task<IActionResult>Deactivate(Guid id,CancellationToken ct)=>Active(id,false,ct);
 async Task<IActionResult>Active(Guid id,bool active,CancellationToken ct){var x=await db.FinancialAccounts.FindAsync([id],ct);if(x is null)return NotFound();x.IsActive=active;CustomerFinanceSupport.Audit(db,this,active?"Financial Account Activated":"Financial Account Deactivated",x.Id,new{active});await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.IsActive}));}
 async Task<string?>Validate(FinancialAccountRequest r,Guid? id,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name))return"Hesap adı zorunludur.";if(!Types.Contains(r.AccountType))return"Geçersiz hesap türü.";if(string.IsNullOrWhiteSpace(r.Currency))return"Para birimi zorunludur.";var iban=Clean(r.Iban);if(iban!=null&&await db.FinancialAccounts.AnyAsync(x=>x.Iban==iban&&x.IsActive&&x.Id!=id,ct))return"Aynı IBAN ile aktif banka hesabı zaten var.";return null;}static string?Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Replace(" ","").ToUpper();
}
public record FinancialAccountListDto(Guid Id,string AccountCode,string Name,string AccountType,string Currency,string? BankName,string? Iban,decimal OpeningBalance,decimal CurrentBalance,DateTime? LastTransactionDate,bool IsActive);
public record FinancialAccountRequest(string Name,string AccountType,string Currency,string? BankName,string? BranchName,string? Iban,string? AccountNumber,decimal OpeningBalance,DateTime OpeningBalanceDate,string? Notes);
