using Asp.Versioning;using Fixar.API.Security;using Fixar.Application.Common.Interfaces;using Fixar.Application.Common.Models;using Fixar.Domain.Entities;using Fixar.Infrastructure.Identity;using Fixar.Infrastructure.Persistence;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace Fixar.API.Controllers;

public static class MaintenanceSupport
{
 public static async Task<string> Next(ApplicationDbContext db,string prefix,DateTime date,CancellationToken ct){await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(81410)",ct);var p=$"{prefix}-{date:yyyyMMdd}-";var values=await (prefix=="MRQ"?db.MaintenanceRequests.Select(x=>x.RequestNumber):db.MaintenanceWorkOrders.Select(x=>x.MaintenanceWorkOrderNumber)).Where(x=>x.StartsWith(p)).ToListAsync(ct);return $"{p}{values.Select(x=>int.TryParse(x[p.Length..],out var n)?n:0).DefaultIfEmpty().Max()+1:0000}";}
 public static object Asset(MaintenanceAsset x)=>new{x.Id,x.AssetCode,x.AssetName,x.AssetType,x.MachineId,x.InjectionStationId,x.CuttingMachineId,x.MoldId,x.Manufacturer,x.Model,x.SerialNumber,x.CommissioningDate,x.Location,x.Criticality,x.ResponsibleUserId,x.MaintenanceStrategy,x.IsActive,x.Notes};
 public static DateTime NextDue(DateTime date,string type,int value)=>type switch{"Daily"=>date.AddDays(value),"Weekly"=>date.AddDays(7*value),"Monthly"=>date.AddMonths(value),"Quarterly"=>date.AddMonths(3*value),"SemiAnnual"=>date.AddMonths(6*value),"Annual"=>date.AddYears(value),_=>date};
}

[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/maintenance-assets"),Authorize(Policy=AuthorizationPolicies.CanViewMaintenance)]
public class MaintenanceAssetsController(ApplicationDbContext db):ControllerBase
{
 [HttpGet]public async Task<IActionResult>List(string? assetType,string? criticality,string? strategy,bool? isActive,Guid? responsibleUserId,string? search,CancellationToken ct){var q=db.MaintenanceAssets.AsNoTracking().AsQueryable();if(assetType!=null)q=q.Where(x=>x.AssetType==assetType);if(criticality!=null)q=q.Where(x=>x.Criticality==criticality);if(strategy!=null)q=q.Where(x=>x.MaintenanceStrategy==strategy);if(isActive.HasValue)q=q.Where(x=>x.IsActive==isActive);if(responsibleUserId.HasValue)q=q.Where(x=>x.ResponsibleUserId==responsibleUserId);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.AssetCode.Contains(search)||x.AssetName.Contains(search));return Ok(ApiResponse<object>.SuccessResponse(await q.OrderBy(x=>x.AssetCode).Select(x=>new{x.Id,x.AssetCode,x.AssetName,x.AssetType,x.Criticality,x.MaintenanceStrategy,x.Location,x.ResponsibleUserId,x.IsActive}).ToListAsync(ct)));}
 [HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken ct){var x=await db.MaintenanceAssets.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);return x is null?NotFound(ApiResponse<object>.Fail("Bakım varlığı bulunamadı.")):Ok(ApiResponse<object>.SuccessResponse(MaintenanceSupport.Asset(x)));}
 [HttpPost,Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceWorkOrders)]public async Task<IActionResult>Create(MaintenanceAssetRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.AssetCode)||string.IsNullOrWhiteSpace(r.AssetName))return BadRequest(ApiResponse<object>.Fail("Varlık kodu ve adı zorunludur."));if(new Guid?[]{r.MachineId,r.InjectionStationId,r.CuttingMachineId,r.MoldId}.Count(x=>x.HasValue)>1)return BadRequest(ApiResponse<object>.Fail("Bir bakım varlığı yalnız bir gerçek hedefe bağlanabilir."));if(await Duplicate(r,null,ct))return Conflict(ApiResponse<object>.Fail("Bu gerçek ekipman için aktif bakım varlığı zaten mevcut."));var x=new MaintenanceAsset{Id=Guid.NewGuid(),AssetCode=r.AssetCode.Trim(),AssetName=r.AssetName.Trim(),AssetType=r.AssetType,MachineId=r.MachineId,InjectionStationId=r.InjectionStationId,CuttingMachineId=r.CuttingMachineId,MoldId=r.MoldId,Manufacturer=r.Manufacturer,Model=r.Model,SerialNumber=r.SerialNumber,Location=r.Location,Criticality=r.Criticality,MaintenanceStrategy=r.MaintenanceStrategy,Notes=r.Notes};db.Add(x);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(MaintenanceSupport.Asset(x)));}
 [HttpPut("{id:guid}"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceWorkOrders)]public async Task<IActionResult>Update(Guid id,MaintenanceAssetRequest r,CancellationToken ct){var x=await db.MaintenanceAssets.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Bakım varlığı bulunamadı."));if(await Duplicate(r,id,ct))return Conflict(ApiResponse<object>.Fail("Bu gerçek ekipman için aktif bakım varlığı zaten mevcut."));x.AssetName=r.AssetName;x.Manufacturer=r.Manufacturer;x.Model=r.Model;x.SerialNumber=r.SerialNumber;x.Location=r.Location;x.Criticality=r.Criticality;x.MaintenanceStrategy=r.MaintenanceStrategy;x.ResponsibleUserId=r.ResponsibleUserId;x.Notes=r.Notes;await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(MaintenanceSupport.Asset(x)));}
 [HttpPost("{id:guid}/activate"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceWorkOrders)]public Task<IActionResult>Activate(Guid id,CancellationToken ct)=>Toggle(id,true,ct);[HttpPost("{id:guid}/deactivate"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceWorkOrders)]public Task<IActionResult>Deactivate(Guid id,CancellationToken ct)=>Toggle(id,false,ct);
 [HttpGet("{id:guid}/history")]public async Task<IActionResult>History(Guid id,CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(await db.MaintenanceWorkOrders.AsNoTracking().Where(x=>x.MaintenanceAssetId==id).OrderByDescending(x=>x.PlannedStart).Select(x=>new{x.Id,x.MaintenanceWorkOrderNumber,x.WorkType,x.Title,x.Status,x.PlannedStart,x.ActualStart,x.ActualEnd,x.DowntimeMinutes,x.TotalMaintenanceCost,x.Currency}).ToListAsync(ct)));
 [HttpGet("{id:guid}/summary")]public async Task<IActionResult>Summary(Guid id,CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(new{OpenRequests=await db.MaintenanceRequests.CountAsync(x=>x.MaintenanceAssetId==id&&x.Status!="Closed"&&x.Status!="Cancelled",ct),WorkOrders=await db.MaintenanceWorkOrders.CountAsync(x=>x.MaintenanceAssetId==id,ct),DowntimeMinutes=await db.MaintenanceWorkOrders.Where(x=>x.MaintenanceAssetId==id).SumAsync(x=>x.DowntimeMinutes,ct),TotalCost=await db.MaintenanceWorkOrders.Where(x=>x.MaintenanceAssetId==id).SumAsync(x=>x.TotalMaintenanceCost??0,ct)}));
 [HttpGet("backfill-preview")]public async Task<IActionResult>Preview(CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(new{Machines=await db.Machines.CountAsync(ct),InjectionStations=await db.InjectionStations.CountAsync(ct),CuttingMachines=await db.CuttingMachines.CountAsync(ct),Molds=await db.Molds.CountAsync(ct),ExistingAssets=await db.MaintenanceAssets.CountAsync(ct),Warning="Önizleme veri oluşturmaz; backfill yalnız seçili kimliklerle yapılır."}));
 [HttpPost("backfill"),Authorize(Policy=AuthorizationPolicies.CanManagePreventiveMaintenance),Idempotent]public async Task<IActionResult>Backfill(BackfillRequest r,CancellationToken ct){var made=0;foreach(var id in r.Ids.Distinct()){var exists=r.AssetType switch{"Machine"=>await db.MaintenanceAssets.AnyAsync(x=>x.MachineId==id&&x.IsActive,ct),"InjectionStation"=>await db.MaintenanceAssets.AnyAsync(x=>x.InjectionStationId==id&&x.IsActive,ct),"CuttingMachine"=>await db.MaintenanceAssets.AnyAsync(x=>x.CuttingMachineId==id&&x.IsActive,ct),"Mold"=>await db.MaintenanceAssets.AnyAsync(x=>x.MoldId==id&&x.IsActive,ct),_=>true};if(exists)continue;db.MaintenanceAssets.Add(new MaintenanceAsset{Id=Guid.NewGuid(),AssetCode=$"{r.AssetType.ToUpperInvariant()}-{id.ToString()[..8]}",AssetName=$"{r.AssetType} {id.ToString()[..8]}",AssetType=r.AssetType,MachineId=r.AssetType=="Machine"?id:null,InjectionStationId=r.AssetType=="InjectionStation"?id:null,CuttingMachineId=r.AssetType=="CuttingMachine"?id:null,MoldId=r.AssetType=="Mold"?id:null});made++;}await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{Created=made}));}
 async Task<bool>Duplicate(MaintenanceAssetRequest r,Guid? id,CancellationToken ct)=>await db.MaintenanceAssets.AnyAsync(x=>x.IsActive&&x.Id!=id&&((r.MachineId!=null&&x.MachineId==r.MachineId)||(r.InjectionStationId!=null&&x.InjectionStationId==r.InjectionStationId)||(r.CuttingMachineId!=null&&x.CuttingMachineId==r.CuttingMachineId)||(r.MoldId!=null&&x.MoldId==r.MoldId)),ct);async Task<IActionResult>Toggle(Guid id,bool active,CancellationToken ct){var x=await db.MaintenanceAssets.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Bakım varlığı bulunamadı."));x.IsActive=active;await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.IsActive}));}
}

[ApiController,ApiVersion("1.0"),Route("api/v{version:apiVersion}/maintenance-requests"),Authorize(Policy=AuthorizationPolicies.CanViewMaintenance)]
public class MaintenanceRequestsController(ApplicationDbContext db,ICurrentUserService user):ControllerBase
{
 [HttpGet]public async Task<IActionResult>List(string? status,string? priority,Guid? assetId,CancellationToken ct){var q=db.MaintenanceRequests.AsNoTracking().AsQueryable();if(status!=null)q=q.Where(x=>x.Status==status);if(priority!=null)q=q.Where(x=>x.Priority==priority);if(assetId.HasValue)q=q.Where(x=>x.MaintenanceAssetId==assetId);return Ok(ApiResponse<object>.SuccessResponse(await q.OrderByDescending(x=>x.ReportedAt).Select(x=>new{x.Id,x.RequestNumber,x.MaintenanceAssetId,Asset=x.MaintenanceAsset.AssetName,x.RequestType,x.Priority,x.Title,x.ReportedAt,x.ReportedByName,x.ProductionImpact,x.MachineStopped,x.AssignedToName,x.Status,x.WorkOrderId}).ToListAsync(ct)));}
 [HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id,CancellationToken ct){var x=await db.MaintenanceRequests.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.RequestNumber,x.MaintenanceAssetId,Asset=x.MaintenanceAsset.AssetName,x.RequestType,x.Priority,x.Title,x.Description,x.ReportedAt,x.ReportedByName,x.ProductionImpact,x.MachineStopped,x.DowntimeStartedAt,x.RelatedDowntimeId,x.Status,x.AssignedToUserId,x.AssignedToName,x.WorkOrderId,x.ResolutionSummary,x.CancellationReason}).FirstOrDefaultAsync(ct);return x is null?NotFound(ApiResponse<object>.Fail("Bakım talebi bulunamadı.")):Ok(ApiResponse<object>.SuccessResponse(x));}
 [HttpPost,Authorize(Policy=AuthorizationPolicies.CanCreateMaintenanceRequest),Idempotent]public async Task<IActionResult>Create(MaintenanceRequestInput r,CancellationToken ct){if(!await db.MaintenanceAssets.AnyAsync(x=>x.Id==r.MaintenanceAssetId&&x.IsActive,ct))return NotFound(ApiResponse<object>.Fail("Bakım varlığı bulunamadı."));if(string.IsNullOrWhiteSpace(r.Title)||string.IsNullOrWhiteSpace(r.Description))return BadRequest(ApiResponse<object>.Fail("Başlık ve açıklama zorunludur."));if(await db.MaintenanceRequests.AnyAsync(x=>x.MaintenanceAssetId==r.MaintenanceAssetId&&x.Title==r.Title&&x.Status!="Closed"&&x.Status!="Cancelled",ct))return Conflict(ApiResponse<object>.Fail("Bu ekipman için açık bakım talebi zaten mevcut."));var now=DateTime.UtcNow;var x=new MaintenanceRequest{Id=Guid.NewGuid(),RequestNumber=await MaintenanceSupport.Next(db,"MRQ",now,ct),MaintenanceAssetId=r.MaintenanceAssetId,RequestType=r.RequestType,Priority=r.Priority,Title=r.Title,Description=r.Description,ReportedAt=now,ReportedByUserId=user.UserId,ReportedByName=user.UserName,ProductionImpact=r.ProductionImpact,MachineStopped=r.MachineStopped,DowntimeStartedAt=r.MachineStopped?r.DowntimeStartedAt??now:null};db.Add(x);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.RequestNumber,x.Status}));}
 [HttpPut("{id:guid}"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests)]public async Task<IActionResult>Update(Guid id,MaintenanceRequestInput r,CancellationToken ct){var x=await db.MaintenanceRequests.FindAsync([id],ct);if(x is null)return NotFound();if(x.Status is "Closed" or "Cancelled")return Conflict(ApiResponse<object>.Fail("Kapalı bakım talebi değiştirilemez."));x.Priority=r.Priority;x.Title=r.Title;x.Description=r.Description;x.ProductionImpact=r.ProductionImpact;await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status}));}
 [HttpPost("{id:guid}/assign"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests),Idempotent]public Task<IActionResult>Assign(Guid id,AssignMaintenance r,CancellationToken ct)=>State(id,"Assigned",r.UserId,r.Name,null,ct);[HttpPost("{id:guid}/start"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests),Idempotent]public Task<IActionResult>Start(Guid id,CancellationToken ct)=>State(id,"InProgress",null,null,null,ct);[HttpPost("{id:guid}/resolve"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests),Idempotent]public Task<IActionResult>Resolve(Guid id,ReasonInput r,CancellationToken ct)=>State(id,"Resolved",null,null,r.Reason,ct);[HttpPost("{id:guid}/close"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests),Idempotent]public async Task<IActionResult>Close(Guid id,CancellationToken ct){if(await db.MaintenanceWorkOrders.AnyAsync(x=>x.MaintenanceRequestId==id&&x.Status!="Closed"&&x.Status!="Cancelled",ct))return Conflict(ApiResponse<object>.Fail("Açık bakım iş emri varken talep kapatılamaz."));return await State(id,"Closed",null,null,null,ct);}[HttpPost("{id:guid}/cancel"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceRequests),Idempotent]public async Task<IActionResult>Cancel(Guid id,ReasonInput r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("İptal gerekçesi zorunludur."));var result=await State(id,"Cancelled",null,null,r.Reason,ct);return result;}
 [HttpPost("{id:guid}/create-work-order"),Authorize(Policy=AuthorizationPolicies.CanManageMaintenanceWorkOrders),Idempotent]public async Task<IActionResult>CreateWorkOrder(Guid id,CancellationToken ct){var req=await db.MaintenanceRequests.FindAsync([id],ct);if(req is null)return NotFound(ApiResponse<object>.Fail("Bakım talebi bulunamadı."));if(await db.MaintenanceWorkOrders.AnyAsync(x=>x.MaintenanceRequestId==id&&x.Status!="Closed"&&x.Status!="Cancelled",ct))return Conflict(ApiResponse<object>.Fail("Bu talep için açık bakım iş emri zaten mevcut."));var x=new MaintenanceWorkOrder{Id=Guid.NewGuid(),MaintenanceWorkOrderNumber=await MaintenanceSupport.Next(db,"MWO",DateTime.UtcNow,ct),MaintenanceAssetId=req.MaintenanceAssetId,MaintenanceRequestId=id,WorkType="Corrective",Priority=req.Priority,Title=req.Title,Description=req.Description,Status="Assigned",PlannedStart=DateTime.UtcNow,AssignedToUserId=req.AssignedToUserId,AssignedToName=req.AssignedToName,RequiresProductionStop=req.MachineStopped};db.Add(x);req.WorkOrderId=x.Id;req.Status="Assigned";await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.MaintenanceWorkOrderNumber,x.Status}));}
 [HttpGet("summary")]public async Task<IActionResult>Summary(CancellationToken ct)=>Ok(ApiResponse<object>.SuccessResponse(new{Open=await db.MaintenanceRequests.CountAsync(x=>x.Status=="Open",ct),Critical=await db.MaintenanceRequests.CountAsync(x=>x.Priority=="Critical"&&x.Status!="Closed"&&x.Status!="Cancelled",ct),InProgress=await db.MaintenanceRequests.CountAsync(x=>x.Status=="InProgress",ct)}));
 async Task<IActionResult>State(Guid id,string state,Guid? uid,string? name,string? reason,CancellationToken ct){var x=await db.MaintenanceRequests.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Bakım talebi bulunamadı."));if(x.Status is "Closed" or "Cancelled")return Conflict(ApiResponse<object>.Fail("Terminal bakım talebi değiştirilemez."));x.Status=state;if(uid.HasValue){x.AssignedToUserId=uid;x.AssignedToName=name;}if(state=="Resolved")x.ResolutionSummary=reason;if(state=="Cancelled"){x.CancelledAt=DateTime.UtcNow;x.CancelledBy=user.UserId;x.CancellationReason=reason;}await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.SuccessResponse(new{x.Id,x.Status}));}
}

public record MaintenanceAssetRequest(string AssetCode,string AssetName,string AssetType,Guid? MachineId,Guid? InjectionStationId,Guid? CuttingMachineId,Guid? MoldId,string? Manufacturer,string? Model,string? SerialNumber,string? Location,string Criticality,string MaintenanceStrategy,Guid? ResponsibleUserId,string? Notes);public record BackfillRequest(string AssetType,List<Guid> Ids);public record MaintenanceRequestInput(Guid MaintenanceAssetId,string RequestType,string Priority,string Title,string Description,string ProductionImpact,bool MachineStopped,DateTime? DowntimeStartedAt);public record AssignMaintenance(Guid UserId,string Name);public record ReasonInput(string Reason);
