using System.Data;
using System.Text.Json;
using Asp.Versioning;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Domain.Enums;
using Fixar.Infrastructure.Persistence;
using Fixar.Infrastructure.Identity;
using Fixar.API.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fixar.API.Controllers;

[ApiController, ApiVersion("1.0"), Authorize]
[Route("api/v{version:apiVersion}/material-consumptions")]
public sealed class MaterialConsumptionsController(ApplicationDbContext db) : ControllerBase
{
    private static readonly string[] Types = ["Production", "Setup", "Sample", "Waste", "Correction"];

    [HttpGet]
    public async Task<IActionResult> GetAll(Guid? workOrderId, Guid? stationAssignmentId, Guid? stockReservationId, Guid? materialId, Guid? materialLotId, Guid? materialContainerId, string? consumptionType, bool? isReversed, DateTime? dateFrom, DateTime? dateTo, string? search, CancellationToken ct)
    {
        var q = db.MaterialConsumptions.AsNoTracking().AsQueryable(); if (workOrderId.HasValue) q = q.Where(x => x.WorkOrderId == workOrderId); if (stationAssignmentId.HasValue) q = q.Where(x => x.StationAssignmentId == stationAssignmentId); if (stockReservationId.HasValue) q = q.Where(x => x.StockReservationId == stockReservationId); if (materialId.HasValue) q = q.Where(x => x.MaterialId == materialId); if (materialLotId.HasValue) q = q.Where(x => x.MaterialLotId == materialLotId); if (materialContainerId.HasValue) q = q.Where(x => x.MaterialContainerId == materialContainerId); if (!string.IsNullOrWhiteSpace(consumptionType)) q = q.Where(x => x.ConsumptionType == consumptionType); if (isReversed.HasValue) q = q.Where(x => x.IsReversed == isReversed); if (dateFrom.HasValue) q = q.Where(x => x.ConsumptionDate >= dateFrom); if (dateTo.HasValue) q = q.Where(x => x.ConsumptionDate <= dateTo); if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToLower(); q = q.Where(x => x.ConsumptionNumber.ToLower().Contains(s) || x.WorkOrder.WorkOrderNumber.ToLower().Contains(s) || x.Material.Name.ToLower().Contains(s) || x.MaterialLot.LotNumber.ToLower().Contains(s)); }
        return Ok(ApiResponse<object>.SuccessResponse(await q.OrderByDescending(x => x.ConsumptionDate).Select(List()).ToListAsync(ct)));
    }
    [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id, CancellationToken ct) { var x = await Detail(id).FirstOrDefaultAsync(ct); return x is null ? NotFound(Fail("Hammadde tüketimi bulunamadı.", "CONSUMPTION_NOT_FOUND")) : Ok(ApiResponse<object>.SuccessResponse(x)); }
    [HttpGet("work-order/{id:guid}")] public async Task<IActionResult> ByWorkOrder(Guid id, CancellationToken ct) => Ok(ApiResponse<object>.SuccessResponse(await db.MaterialConsumptions.AsNoTracking().Where(x => x.WorkOrderId == id).OrderByDescending(x => x.ConsumptionDate).Select(List()).ToListAsync(ct)));
    [HttpGet("reservation/{id:guid}")] public async Task<IActionResult> ByReservation(Guid id, CancellationToken ct) => Ok(ApiResponse<object>.SuccessResponse(await db.MaterialConsumptions.AsNoTracking().Where(x => x.StockReservationId == id).OrderByDescending(x => x.ConsumptionDate).Select(List()).ToListAsync(ct)));
    [HttpGet("summary")]
    public async Task<IActionResult> Summary(CancellationToken ct)
    {
        var today = DateTime.UtcNow.Date; var q = db.MaterialConsumptions.AsNoTracking(); var byType = await q.Where(x => !x.IsReversed).GroupBy(x => x.ConsumptionType).Select(x => new { type = x.Key, quantity = x.Sum(y => y.Quantity), count = x.Count() }).ToListAsync(ct); var recent = await q.OrderByDescending(x => x.ConsumptionDate).Take(5).Select(List()).ToListAsync(ct);
        return Ok(ApiResponse<object>.SuccessResponse(new { totalConsumptionCount = await q.CountAsync(ct), activeConsumptionCount = await q.CountAsync(x => !x.IsReversed, ct), reversedConsumptionCount = await q.CountAsync(x => x.IsReversed, ct), today = await q.CountAsync(x => x.ConsumptionDate >= today, ct), production = await q.CountAsync(x => !x.IsReversed && x.ConsumptionType == "Production", ct), waste = await q.CountAsync(x => !x.IsReversed && x.ConsumptionType == "Waste", ct), quantityByType = byType, recentConsumptions = recent }));
    }

    [HttpPost]
    [Authorize(Policy = AuthorizationPolicies.CanRecordConsumption), Idempotent]
    public async Task<IActionResult> Create([FromBody] ConsumptionRequest request, CancellationToken ct)
    {
        if (request.Quantity <= 0) return BadRequest(Fail("Tüketim miktarı sıfırdan büyük olmalıdır.", "INVALID_QUANTITY")); if (!Types.Contains(request.ConsumptionType)) return BadRequest(Fail("Tüketim tipi geçersiz.", "INVALID_TYPE")); if (string.IsNullOrWhiteSpace(request.Unit)) return BadRequest(Fail("Tüketim birimi zorunludur.", "UNIT_REQUIRED"));
        await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        var line = await db.StockReservationLines.Include(x => x.StockReservation).ThenInclude(x => x.WorkOrder).Include(x => x.StockReservation).ThenInclude(x => x.Lines).Include(x => x.MaterialLot).Include(x => x.MaterialContainer).Include(x => x.StockItem).FirstOrDefaultAsync(x => x.Id == request.StockReservationLineId, ct);
        if (line is null || line.StockReservationId != request.StockReservationId) return BadRequest(Fail("Aktif stok rezervasyonu bulunamadı.", "RESERVATION_NOT_FOUND")); if (line.StockReservation.WorkOrderId != request.WorkOrderId) return BadRequest(Fail("Rezervasyon satırı iş emrine ait değil.", "WORK_ORDER_MISMATCH")); if (line.StockReservation.Status is not ("Active" or "PartiallyConsumed")) return BadRequest(Fail("Aktif stok rezervasyonu bulunamadı.", "RESERVATION_NOT_ACTIVE")); if (line.StockReservation.WorkOrder.IsCancelled || line.StockReservation.WorkOrder.Status is "Completed" or "Cancelled") return BadRequest(Fail("Tamamlanmış veya iptal edilmiş iş emri için tüketim yapılamaz.", "WORK_ORDER_TERMINAL"));
        if (request.StationAssignmentId.HasValue && !await db.StationAssignments.AnyAsync(x => x.Id == request.StationAssignmentId && x.WorkOrderId == request.WorkOrderId, ct)) return BadRequest(Fail("İstasyon ataması iş emrine ait değil.", "ASSIGNMENT_MISMATCH"));
        var lot = line.MaterialLot; var container = line.MaterialContainer; var stock = line.StockItem; if (!string.Equals(request.Unit.Trim(), line.Unit, StringComparison.OrdinalIgnoreCase) || !string.Equals(line.Unit, lot.Unit, StringComparison.OrdinalIgnoreCase) || !string.Equals(line.Unit, stock.Unit, StringComparison.OrdinalIgnoreCase) || (container != null && !string.Equals(line.Unit, container.Unit, StringComparison.OrdinalIgnoreCase))) return BadRequest(Fail("Stok, lot, container ve rezervasyon birimleri uyumlu olmalıdır.", "UNIT_MISMATCH"));
        if (!lot.IsActive || lot.IsBlocked || lot.QualityStatus == "Rejected") return BadRequest(Fail("Blokeli veya kalite reddi bulunan lottan tüketim yapılamaz.", "LOT_UNAVAILABLE")); if (lot.ExpiryDate < DateTime.UtcNow) return BadRequest(Fail("Süresi geçmiş lottan tüketim yapılamaz.", "LOT_EXPIRED")); if (container is null && request.ConsumptionType != "Correction") return BadRequest(Fail("Üretim tüketimi için varil veya fiziksel ambalaj seçilmelidir.", "CONTAINER_REQUIRED")); if (container is null && string.IsNullOrWhiteSpace(request.OverrideReason)) return BadRequest(Fail("Container olmadan düzeltme tüketimi için override gerekçesi zorunludur.", "OVERRIDE_REASON_REQUIRED"));
        if (container is not null) { if (!container.IsActive || container.IsBlocked || container.IsDamaged) return BadRequest(Fail("Hasarlı veya blokeli varilden tüketim yapılamaz.", "CONTAINER_UNAVAILABLE")); if (container.Status is not ("Open" or "PartiallyUsed")) return BadRequest(Fail("Kapalı varilden hammadde tüketimi yapılamaz.", "CONTAINER_CLOSED")); if (container.CurrentQuantity < request.Quantity) return BadRequest(Fail("Tüketim miktarı varildeki mevcut miktarı aşıyor.", "CONTAINER_INSUFFICIENT")); }
        var remaining = line.ReservedQuantity - line.ReleasedQuantity - line.ConsumedQuantity; if (request.Quantity > remaining) return BadRequest(Fail("Tüketim miktarı kalan rezerve miktarı aşıyor.", "RESERVATION_INSUFFICIENT")); if (lot.CurrentQuantity < request.Quantity) return BadRequest(Fail("Tüketim miktarı lot mevcut miktarını aşıyor.", "LOT_INSUFFICIENT")); if (stock.CurrentQuantity < request.Quantity) return BadRequest(Fail("Tüketim miktarı fiziksel stok miktarını aşıyor.", "STOCK_INSUFFICIENT")); if (lot.ReservedQuantity < request.Quantity || (container != null && container.ReservedQuantity < request.Quantity)) return Conflict(Fail("Rezerve miktar tutarsız; işlem uygulanmadı.", "RESERVATION_CONFLICT"));
        var now = DateTime.UtcNow; var actor = Actor(); var consumption = new MaterialConsumption { Id = Guid.NewGuid(), ConsumptionNumber = await GenerateNumber(now, ct), WorkOrderId = request.WorkOrderId, StationAssignmentId = request.StationAssignmentId, StockReservationId = line.StockReservationId, StockReservationLineId = line.Id, MaterialId = line.MaterialId, StockItemId = line.StockItemId, MaterialLotId = line.MaterialLotId, MaterialContainerId = line.MaterialContainerId, ConsumptionDate = now, Quantity = request.Quantity, Unit = line.Unit, ConsumptionType = request.ConsumptionType, Notes = Clean(request.Notes) };
        var before = stock.CurrentQuantity; stock.CurrentQuantity -= request.Quantity; lot.CurrentQuantity -= request.Quantity; lot.ReservedQuantity -= request.Quantity; if (container != null) { container.CurrentQuantity -= request.Quantity; container.ReservedQuantity -= request.Quantity; UpdateContainerStatus(container); } UpdateLotStatus(lot); line.ConsumedQuantity += request.Quantity; line.LastConsumedAt = now; line.LastConsumedByName = actor; line.UpdatedAt = now;
        var movement = new StockMovement { Id = Guid.NewGuid(), StockItemId = stock.Id, MovementType = request.ConsumptionType + "Consumption", Quantity = request.Quantity, MovementDate = now, SourceType = "MaterialConsumption", SourceDocumentNo = consumption.ConsumptionNumber, Note = $"{line.StockReservation.WorkOrder.WorkOrderNumber}; önce {before} {stock.Unit}, sonra {stock.CurrentQuantity} {stock.Unit}. {Clean(request.Notes)}" }; consumption.StockMovementId = movement.Id; db.MaterialConsumptions.Add(consumption); db.StockMovements.Add(movement); UpdateReservationStatus(line.StockReservation);
        Audit("Material Consumption Created", consumption.Id, new { consumption.ConsumptionNumber, consumption.Quantity, consumption.Unit }); Audit(request.ConsumptionType + " Consumption Created", consumption.Id, new { consumption.WorkOrderId, consumption.MaterialLotId, consumption.MaterialContainerId }); if (container is null) Audit("Consumption Without Container Override", consumption.Id, new { request.OverrideReason }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct);
        return CreatedAtAction(nameof(Get), new { id = consumption.Id, version = "1" }, ApiResponse<object>.SuccessResponse(await Detail(consumption.Id).FirstAsync(ct), "Hammadde tüketimi kaydedildi."));
    }

    [HttpPost("{id:guid}/reverse")]
    [Authorize(Policy = AuthorizationPolicies.CanReverseConsumption), Idempotent]
    public async Task<IActionResult> Reverse(Guid id, [FromBody] ReverseRequest request, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(request.Reason)) return BadRequest(Fail("Geri alma gerekçesi zorunludur.", "REASON_REQUIRED")); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var c = await db.MaterialConsumptions.Include(x => x.StockReservation).Include(x => x.StockReservationLine).Include(x => x.StockItem).Include(x => x.MaterialLot).Include(x => x.MaterialContainer).FirstOrDefaultAsync(x => x.Id == id, ct); if (c is null) return NotFound(Fail("Hammadde tüketimi bulunamadı.", "CONSUMPTION_NOT_FOUND")); if (c.IsReversed) return BadRequest(Fail("Bu tüketim daha önce geri alınmış.", "ALREADY_REVERSED")); if (c.StockReservationLine.ConsumedQuantity < c.Quantity) return Conflict(Fail("Rezervasyon tüketim miktarı tutarsız.", "CONSUMPTION_CONFLICT")); if (c.MaterialLot.CurrentQuantity + c.Quantity > c.MaterialLot.InitialQuantity || (c.MaterialContainer != null && c.MaterialContainer.CurrentQuantity + c.Quantity > c.MaterialContainer.InitialQuantity)) return BadRequest(Fail("Geri alma sonrası miktar başlangıç miktarını aşamaz.", "INITIAL_QUANTITY_EXCEEDED"));
        var now = DateTime.UtcNow; var stockBefore = c.StockItem.CurrentQuantity; c.StockItem.CurrentQuantity += c.Quantity; c.MaterialLot.CurrentQuantity += c.Quantity; if (c.MaterialContainer != null) c.MaterialContainer.CurrentQuantity += c.Quantity; c.StockReservationLine.ConsumedQuantity -= c.Quantity; c.StockReservationLine.UpdatedAt = now; var canReopen = c.StockReservation.Status is "Active" or "PartiallyConsumed" or "Consumed"; if (canReopen) { c.MaterialLot.ReservedQuantity += c.Quantity; if (c.MaterialContainer != null) c.MaterialContainer.ReservedQuantity += c.Quantity; c.StockReservation.Status = c.StockReservationLine.ConsumedQuantity > 0 ? "PartiallyConsumed" : "Active"; c.StockReservation.UpdatedAt = now; } UpdateLotStatus(c.MaterialLot); if (c.MaterialContainer != null) UpdateContainerStatus(c.MaterialContainer);
        var movement = new StockMovement { Id = Guid.NewGuid(), StockItemId = c.StockItemId, MovementType = "ConsumptionReversal", Quantity = c.Quantity, MovementDate = now, SourceType = "MaterialConsumption", SourceDocumentNo = c.ConsumptionNumber, Note = $"Geri alma: {request.Reason.Trim()}; önce {stockBefore} {c.Unit}, sonra {c.StockItem.CurrentQuantity} {c.Unit}" }; db.StockMovements.Add(movement); c.IsReversed = true; c.ReversedAt = now; c.ReversedByName = Actor(); c.ReversalReason = request.Reason.Trim(); c.ReversalStockMovementId = movement.Id; Audit("Material Consumption Reversed", c.Id, new { c.ConsumptionNumber, c.Quantity, c.ReversalReason, ReservationReopened = canReopen }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(await Detail(id).FirstAsync(ct), "Tüketim geri alındı."));
    }

    private static System.Linq.Expressions.Expression<Func<MaterialConsumption, object>> List() => x => new { x.Id, x.ConsumptionNumber, x.ConsumptionDate, x.WorkOrderId, x.WorkOrder.WorkOrderNumber, x.StationAssignmentId, x.StockReservation.ReservationNumber, x.MaterialId, MaterialCode = x.Material.Code, MaterialName = x.Material.Name, LotNumber = x.MaterialLot.LotNumber, ContainerCode = x.MaterialContainer != null ? x.MaterialContainer.ContainerCode : null, x.Quantity, x.Unit, x.ConsumptionType, x.IsReversed, CreatedBy = x.CreatedBy, CreatedAt = x.Created };
    private IQueryable<object> Detail(Guid id) => db.MaterialConsumptions.AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, x.ConsumptionNumber, x.ConsumptionDate, x.WorkOrderId, WorkOrder = new { x.WorkOrder.WorkOrderNumber, x.WorkOrder.Status }, x.StationAssignmentId, x.StockReservationId, Reservation = new { x.StockReservation.ReservationNumber, x.StockReservation.Status }, x.StockReservationLineId, x.MaterialId, Material = new { x.Material.Code, x.Material.Name }, x.StockItemId, Stock = new { x.StockItem.Code, x.StockItem.Name, x.StockItem.Unit }, x.MaterialLotId, Lot = new { x.MaterialLot.LotNumber, x.MaterialLot.Status }, x.MaterialContainerId, Container = x.MaterialContainer == null ? null : new { x.MaterialContainer.ContainerCode, x.MaterialContainer.Status }, x.Quantity, x.Unit, x.ConsumptionType, x.Notes, x.StockMovementId, x.IsReversed, x.ReversedAt, x.ReversedByName, x.ReversalReason, x.ReversalStockMovementId, x.Created, x.CreatedBy, x.LastModified, x.LastModifiedBy });
    private static void UpdateContainerStatus(MaterialContainer x) { if (x.IsDamaged) x.Status = "Damaged"; else if (x.IsBlocked) x.Status = "Blocked"; else if (x.CurrentQuantity <= 0) x.Status = "Empty"; else if (x.OpenedAt.HasValue) x.Status = x.CurrentQuantity < x.InitialQuantity ? "PartiallyUsed" : "Open"; else x.Status = "Sealed"; x.UpdatedAt = DateTime.UtcNow; }
    private static void UpdateLotStatus(MaterialLot x) { if (x.IsBlocked) x.Status = "Blocked"; else if (x.ExpiryDate < DateTime.UtcNow) x.Status = "Expired"; else if (x.CurrentQuantity <= 0) x.Status = "FullyUsed"; else if (x.CurrentQuantity < x.InitialQuantity) x.Status = "PartiallyUsed"; else x.Status = "Available"; x.UpdatedAt = DateTime.UtcNow; }
    private static void UpdateReservationStatus(StockReservation r) { var remaining = r.Lines.Sum(x => x.ReservedQuantity - x.ReleasedQuantity - x.ConsumedQuantity); var consumed = r.Lines.Sum(x => x.ConsumedQuantity); if (remaining <= 0 && consumed > 0 && r.Lines.All(x => x.ReleasedQuantity == 0)) r.Status = "Consumed"; else if (consumed > 0) r.Status = "PartiallyConsumed"; else r.Status = "Active"; r.UpdatedAt = DateTime.UtcNow; }
    private async Task<string> GenerateNumber(DateTime now, CancellationToken ct) { var prefix = $"CONS-{now:yyyyMMdd}-"; await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(hashtext({0}))", [prefix], ct); var last = await db.MaterialConsumptions.Where(x => x.ConsumptionNumber.StartsWith(prefix)).OrderByDescending(x => x.ConsumptionNumber).Select(x => x.ConsumptionNumber).FirstOrDefaultAsync(ct); var next = last?.Length >= 4 && int.TryParse(last[^4..], out var n) ? n + 1 : 1; return prefix + next.ToString("0000"); }
    private string Actor() => User?.Identity?.IsAuthenticated == true && !string.IsNullOrWhiteSpace(User.Identity.Name) ? User.Identity.Name : "system"; private static string? Clean(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim(); private static ApiResponse<object> Fail(string message, string code) => ApiResponse<object>.Fail(message, code); private void Audit(string name, Guid id, object payload) => db.AuditLogs.Add(new AuditLog { Id = Guid.NewGuid(), UserName = Actor(), Action = AuditAction.Update, EntityName = name, EntityId = id.ToString(), NewValues = JsonSerializer.Serialize(payload), Timestamp = DateTime.UtcNow, IpAddress = HttpContext.Connection.RemoteIpAddress?.ToString() });
}

public sealed record ConsumptionRequest(Guid WorkOrderId, Guid? StationAssignmentId, Guid StockReservationId, Guid StockReservationLineId, decimal Quantity, string Unit, string ConsumptionType, string? Notes, string? OverrideReason);
public sealed record ReverseRequest(string? Reason);
