using Asp.Versioning;
using Fixar.Application.Common.Models;
using Fixar.Domain.Entities;
using Fixar.Infrastructure.Identity;
using Fixar.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fixar.API.Controllers;

[ApiController, ApiVersion("1.0"), Authorize(Policy = AuthorizationPolicies.CanManageProfitabilitySettings)]
[Route("api/v{version:apiVersion}/profitability-settings")]
public sealed class ProfitabilitySettingsController(ApplicationDbContext db) : ControllerBase
{
    [HttpGet] public async Task<IActionResult> List(CancellationToken ct) => Ok(ApiResponse<object>.SuccessResponse(await db.ProfitabilitySettings.AsNoTracking().OrderByDescending(x => x.EffectiveFrom).ToListAsync(ct)));
    [HttpGet("current")] public async Task<IActionResult> Current(CancellationToken ct) { var now = DateTime.UtcNow; var x = await db.ProfitabilitySettings.AsNoTracking().Where(x => x.IsActive && x.EffectiveFrom <= now && (x.EffectiveTo == null || x.EffectiveTo >= now)).OrderByDescending(x => x.EffectiveFrom).FirstOrDefaultAsync(ct); return x is null ? NotFound(ApiResponse<object>.Fail("Kârlılık raporu ayarı bulunamadı.", "SETTINGS_NOT_FOUND")) : Ok(ApiResponse<object>.SuccessResponse(x)); }
    [HttpPost] public async Task<IActionResult> Create(ProfitabilitySettingsRequest r, CancellationToken ct) { var error = Validate(r); if (error is not null) return BadRequest(ApiResponse<object>.Fail(error, "VALIDATION_ERROR")); if (r.IsActive && await Overlaps(null, r, ct)) return Conflict(ApiResponse<object>.Fail("Aynı dönemde aktif kârlılık ayarı bulunuyor.", "SETTINGS_OVERLAP")); var x = new ProfitabilitySettings(); Apply(x, r); db.ProfitabilitySettings.Add(x); await db.SaveChangesAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(new { x.Id }, "Kârlılık ayarı oluşturuldu.")); }
    [HttpPut("{id:guid}")] public async Task<IActionResult> Update(Guid id, ProfitabilitySettingsRequest r, CancellationToken ct) { var x = await db.ProfitabilitySettings.FirstOrDefaultAsync(x => x.Id == id, ct); if (x is null) return NotFound(ApiResponse<object>.Fail("Kârlılık ayarı bulunamadı.", "SETTINGS_NOT_FOUND")); var error = Validate(r); if (error is not null) return BadRequest(ApiResponse<object>.Fail(error, "VALIDATION_ERROR")); if (r.IsActive && await Overlaps(id, r, ct)) return Conflict(ApiResponse<object>.Fail("Aynı dönemde aktif kârlılık ayarı bulunuyor.", "SETTINGS_OVERLAP")); Apply(x, r); await db.SaveChangesAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(new { x.Id }, "Kârlılık ayarı güncellendi.")); }
    [HttpPost("{id:guid}/activate")] public Task<IActionResult> Activate(Guid id, CancellationToken ct) => Active(id, true, ct); [HttpPost("{id:guid}/deactivate")] public Task<IActionResult> Deactivate(Guid id, CancellationToken ct) => Active(id, false, ct);
    private async Task<IActionResult> Active(Guid id, bool active, CancellationToken ct) { var x = await db.ProfitabilitySettings.FirstOrDefaultAsync(x => x.Id == id, ct); if (x is null) return NotFound(ApiResponse<object>.Fail("Kârlılık ayarı bulunamadı.", "SETTINGS_NOT_FOUND")); var r = From(x, active); if (active && await Overlaps(id, r, ct)) return Conflict(ApiResponse<object>.Fail("Aynı dönemde aktif kârlılık ayarı bulunuyor.", "SETTINGS_OVERLAP")); x.IsActive = active; await db.SaveChangesAsync(ct); return Ok(ApiResponse<object>.SuccessResponse(new { x.Id, x.IsActive })); }
    private Task<bool> Overlaps(Guid? id, ProfitabilitySettingsRequest r, CancellationToken ct) => db.ProfitabilitySettings.AnyAsync(x => x.Id != id && x.IsActive && x.EffectiveFrom <= (r.EffectiveTo ?? DateTime.MaxValue) && (x.EffectiveTo == null || x.EffectiveTo >= r.EffectiveFrom), ct);
    private static string? Validate(ProfitabilitySettingsRequest r) => r.EffectiveTo < r.EffectiveFrom ? "Bitiş tarihi başlangıçtan önce olamaz." : new[] { r.HighMarginThresholdPercent, r.LowMarginThresholdPercent, r.BreakEvenTolerancePercent, r.FireWarningThresholdPercent, r.CostVarianceWarningThresholdPercent, r.MinimumDataCompletenessPercent }.Any(x => x < 0) ? "Eşik değerleri negatif olamaz." : r.HighMarginThresholdPercent < r.LowMarginThresholdPercent ? "Yüksek marj eşiği düşük marj eşiğinden küçük olamaz." : null;
    private static void Apply(ProfitabilitySettings x, ProfitabilitySettingsRequest r) { x.EffectiveFrom=r.EffectiveFrom;x.EffectiveTo=r.EffectiveTo;x.HighMarginThresholdPercent=r.HighMarginThresholdPercent;x.LowMarginThresholdPercent=r.LowMarginThresholdPercent;x.BreakEvenTolerancePercent=r.BreakEvenTolerancePercent;x.FireWarningThresholdPercent=r.FireWarningThresholdPercent;x.CostVarianceWarningThresholdPercent=r.CostVarianceWarningThresholdPercent;x.DeliveryDelayWarningDays=r.DeliveryDelayWarningDays;x.MinimumDataCompletenessPercent=r.MinimumDataCompletenessPercent;x.IsActive=r.IsActive;x.Notes=r.Notes; }
    private static ProfitabilitySettingsRequest From(ProfitabilitySettings x,bool active)=>new(x.EffectiveFrom,x.EffectiveTo,x.HighMarginThresholdPercent,x.LowMarginThresholdPercent,x.BreakEvenTolerancePercent,x.FireWarningThresholdPercent,x.CostVarianceWarningThresholdPercent,x.DeliveryDelayWarningDays,x.MinimumDataCompletenessPercent,active,x.Notes);
}
public sealed record ProfitabilitySettingsRequest(DateTime EffectiveFrom,DateTime? EffectiveTo,decimal HighMarginThresholdPercent,decimal LowMarginThresholdPercent,decimal BreakEvenTolerancePercent,decimal FireWarningThresholdPercent,decimal CostVarianceWarningThresholdPercent,int DeliveryDelayWarningDays,decimal MinimumDataCompletenessPercent,bool IsActive,string? Notes);
