using Fixar.Application.Common.Interfaces;using Fixar.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace Fixar.Infrastructure.Services;
public class FinancialCashFlowService(ApplicationDbContext db):IFinancialCashFlowService
{
 public async Task<object>GetAccountBalanceAsync(Guid id,CancellationToken ct){var x=await db.FinancialAccounts.AsNoTracking().Where(a=>a.Id==id).Select(a=>new{a.Id,a.AccountCode,a.Name,a.Currency,a.OpeningBalance,Inflow=db.FinancialTransactions.Where(t=>t.FinancialAccountId==a.Id&&!t.IsReversed&&t.Direction=="Inflow").Sum(t=>(decimal?)t.Amount)??0,Outflow=db.FinancialTransactions.Where(t=>t.FinancialAccountId==a.Id&&!t.IsReversed&&t.Direction=="Outflow").Sum(t=>(decimal?)t.Amount)??0}).FirstOrDefaultAsync(ct)??throw new InvalidOperationException("Finans hesabı bulunamadı.");return new{x.Id,x.AccountCode,x.Name,x.Currency,x.OpeningBalance,x.Inflow,x.Outflow,CurrentBalance=x.OpeningBalance+x.Inflow-x.Outflow};}
 public async Task<IReadOnlyList<object>>GetBalancesAsync(CancellationToken ct)=>(await db.FinancialAccounts.AsNoTracking().Select(a=>new{a.Id,a.AccountCode,a.Name,a.AccountType,a.Currency,a.OpeningBalance,Movement=db.FinancialTransactions.Where(t=>t.FinancialAccountId==a.Id&&!t.IsReversed).Sum(t=>(decimal?)(t.Direction=="Inflow"?t.Amount:-t.Amount))??0,a.IsActive}).ToListAsync(ct)).Select(x=>(object)new{x.Id,x.AccountCode,x.Name,x.AccountType,x.Currency,Balance=x.OpeningBalance+x.Movement,x.IsActive}).ToList();
 public Task<IReadOnlyList<object>>GetCashFlowAsync(DateTime f,DateTime t,string? c,CancellationToken ct)=>GetDailyCashFlowAsync(f,t,c,ct);
 public async Task<IReadOnlyList<object>>GetDailyCashFlowAsync(DateTime f,DateTime t,string? c,CancellationToken ct){var q=db.FinancialTransactions.AsNoTracking().Where(x=>!x.IsReversed&&x.TransactionDate>=f&&x.TransactionDate<t);if(!string.IsNullOrWhiteSpace(c))q=q.Where(x=>x.Currency==c.ToUpper());var raw=await q.Select(x=>new{x.TransactionDate,x.Currency,x.Direction,x.TransactionType,x.SourceType,x.Amount,x.FinancialAccount.AccountType}).ToListAsync(ct);return raw.GroupBy(x=>new{x.TransactionDate.Date,x.Currency}).Select(g=>(object)new{Date=g.Key.Date,g.Key.Currency,Inflow=g.Where(x=>x.Direction=="Inflow").Sum(x=>x.Amount),Outflow=g.Where(x=>x.Direction=="Outflow").Sum(x=>x.Amount),NetCashFlow=g.Where(x=>x.TransactionType!="AccountTransfer").Sum(x=>x.Direction=="Inflow"?x.Amount:-x.Amount),CashInflow=g.Where(x=>x.Direction=="Inflow"&&x.AccountType=="Cash").Sum(x=>x.Amount),BankInflow=g.Where(x=>x.Direction=="Inflow"&&x.AccountType=="Bank").Sum(x=>x.Amount),CreditCardInflow=g.Where(x=>x.Direction=="Inflow"&&x.AccountType=="CreditCardClearing").Sum(x=>x.Amount),ChequeCollectionInflow=g.Where(x=>x.TransactionType=="ChequeCollection"&&x.Direction=="Inflow").Sum(x=>x.Amount),ManualInflow=g.Where(x=>x.TransactionType=="ManualIncome").Sum(x=>x.Amount),ManualOutflow=g.Where(x=>x.TransactionType=="ManualExpense").Sum(x=>x.Amount),TransferIn=g.Where(x=>x.TransactionType=="AccountTransfer"&&x.Direction=="Inflow").Sum(x=>x.Amount),TransferOut=g.Where(x=>x.TransactionType=="AccountTransfer"&&x.Direction=="Outflow").Sum(x=>x.Amount),TransactionCount=g.Count()}).OrderBy(x=>((dynamic)x).Date).ToList();}
 public async Task<IReadOnlyList<object>>GetMonthlyCashFlowAsync(DateTime f,DateTime t,string? c,CancellationToken ct){var daily=await GetDailyCashFlowAsync(f,t,c,ct);return daily;}
 public async Task<IReadOnlyList<object>>GetPaymentMethodBreakdownAsync(DateTime f,DateTime t,CancellationToken ct)=>(await db.CustomerCollections.AsNoTracking().Where(x=>!x.IsReversed&&x.Status!="Draft"&&x.Status!="Cancelled"&&x.CollectionDate>=f&&x.CollectionDate<t).GroupBy(x=>new{x.Currency,x.PaymentMethod}).Select(g=>new{g.Key.Currency,g.Key.PaymentMethod,Amount=g.Sum(x=>x.Amount),Count=g.Count()}).ToListAsync(ct)).Cast<object>().ToList();
 public async Task<IReadOnlyList<object>>GetChequeMaturityAsync(CancellationToken ct){var today=DateTime.UtcNow.Date;return(await db.CustomerCheques.AsNoTracking().Where(x=>x.Status=="InPortfolio"||x.Status=="DepositedToBank").Select(x=>new{x.Id,x.PortfolioNumber,Customer=x.Customer.CompanyName??x.Customer.Name,x.DueDate,x.Currency,x.Amount,x.Status}).ToListAsync(ct)).Select(x=>(object)new{x.Id,x.PortfolioNumber,x.Customer,x.DueDate,x.Currency,x.Amount,x.Status,Bucket=x.DueDate<today?"Overdue":x.DueDate==today?"Today":x.DueDate<=today.AddDays(7)?"Next7Days":x.DueDate<=today.AddDays(30)?"Next30Days":x.DueDate<=today.AddDays(60)?"Next60Days":"Later"}).ToList();}
 public async Task<IReadOnlyList<object>>GetLiquiditySummaryAsync(CancellationToken ct){var balances=await db.FinancialAccounts.AsNoTracking().Select(a=>new{a.AccountType,a.Currency,Balance=a.OpeningBalance+(db.FinancialTransactions.Where(t=>t.FinancialAccountId==a.Id&&!t.IsReversed).Sum(t=>(decimal?)(t.Direction=="Inflow"?t.Amount:-t.Amount))??0)}).ToListAsync(ct);var cheques=await db.CustomerCheques.AsNoTracking().ToListAsync(ct);var unposted=await db.CustomerCollections.AsNoTracking().Where(x=>x.Status!="Draft"&&x.Status!="Cancelled"&&!x.IsReversed&&x.FinancePostingStatus=="Pending").GroupBy(x=>x.Currency).Select(g=>new{Currency=g.Key,Amount=g.Sum(x=>x.Amount)}).ToListAsync(ct);var currencies=balances.Select(x=>x.Currency).Concat(cheques.Select(x=>x.Currency)).Concat(unposted.Select(x=>x.Currency)).Distinct();var today=DateTime.UtcNow.Date;return currencies.Select(c=>(object)new{Currency=c,CashBalance=balances.Where(x=>x.Currency==c&&x.AccountType=="Cash").Sum(x=>x.Balance),BankBalance=balances.Where(x=>x.Currency==c&&x.AccountType=="Bank").Sum(x=>x.Balance),CardClearingBalance=balances.Where(x=>x.Currency==c&&x.AccountType=="CreditCardClearing").Sum(x=>x.Balance),TotalLiquidBalance=balances.Where(x=>x.Currency==c&&x.AccountType is "Cash" or "Bank" or "CreditCardClearing").Sum(x=>x.Balance),ChequePortfolioAmount=cheques.Where(x=>x.Currency==c&&x.Status is "InPortfolio" or "DepositedToBank").Sum(x=>x.Amount),ChequesDueIn7Days=cheques.Where(x=>x.Currency==c&&x.DueDate>=today&&x.DueDate<=today.AddDays(7)&&x.Status is "InPortfolio" or "DepositedToBank").Sum(x=>x.Amount),ChequesDueIn30Days=cheques.Where(x=>x.Currency==c&&x.DueDate>=today&&x.DueDate<=today.AddDays(30)&&x.Status is "InPortfolio" or "DepositedToBank").Sum(x=>x.Amount),BouncedChequeAmount=cheques.Where(x=>x.Currency==c&&x.Status=="Bounced").Sum(x=>x.Amount),UnpostedCollectionAmount=unposted.FirstOrDefault(x=>x.Currency==c)?.Amount??0}).ToList();}
}
