// <auto-generated />
using System;
using Fixar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fixar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713134644_AddLiveProduction")]
    partial class AddLiveProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fixar.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.CuttingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CuttingMachines");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.CuttingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CutPairs")
                        .HasColumnType("integer");

                    b.Property<Guid>("CuttingMachineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CuttingMachineId");

                    b.HasIndex("OrderId");

                    b.ToTable("CuttingRecords");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.InjectionStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InjectionStations");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AvailabilityPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentOperatorName")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultCycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("EnergyConsumption")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCleaningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<int?>("MaximumDailyCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextCalibrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextCleaningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("OEE")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PerformancePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("QualityPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int?>("StationCount")
                        .HasColumnType("integer");

                    b.Property<long>("TotalProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalRunningHours")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WorkingHoursPerDay")
                        .HasColumnType("numeric");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AddedToPoliolBatch")
                        .HasColumnType("boolean");

                    b.Property<string>("AdhesiveType")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationNote")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationPosition")
                        .HasColumnType("text");

                    b.Property<string>("BoxDimensions")
                        .HasColumnType("text");

                    b.Property<int?>("BoxPairCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BoxWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ChemicalRole")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ContainerWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CriticalStock")
                        .HasColumnType("numeric");

                    b.Property<string>("CrosskimApplicationNote")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultSupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultSupplierName")
                        .HasColumnType("text");

                    b.Property<decimal?>("Density")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DtfCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("DtfHeight")
                        .HasColumnType("numeric");

                    b.Property<string>("DtfName")
                        .HasColumnType("text");

                    b.Property<decimal?>("DtfWidth")
                        .HasColumnType("numeric");

                    b.Property<bool>("ExpiryTrackingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FabricColor")
                        .HasColumnType("text");

                    b.Property<decimal?>("FabricRollLength")
                        .HasColumnType("numeric");

                    b.Property<string>("FabricType")
                        .HasColumnType("text");

                    b.Property<decimal?>("FabricWeightGsm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FabricWidth")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("LocationCode")
                        .HasColumnType("text");

                    b.Property<bool>("LotTrackingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumStock")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumStock")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MixingRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackagingType")
                        .HasColumnType("text");

                    b.Property<string>("SafetyInformation")
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSpecification")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Mold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("CadFilePath")
                        .HasColumnType("text");

                    b.Property<int>("CavityCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompatibleMachineCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentStationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("EstimatedLifeCycles")
                        .HasColumnType("bigint");

                    b.Property<string>("FoamType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRightLeftCombined")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCleaningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineName")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaximumPairWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumPairWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelCode")
                        .HasColumnType("text");

                    b.Property<string>("MoldType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MoldWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextCleaningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerCustomerName")
                        .HasColumnType("text");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductModel")
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<int?>("ReleaseFrequencyCycles")
                        .HasColumnType("integer");

                    b.Property<string>("ShelfCode")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SizeGroup")
                        .HasColumnType("text");

                    b.Property<string>("SizeRange")
                        .HasColumnType("text");

                    b.Property<int?>("StandardCuringTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("StandardCycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StandardMoldTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetPairWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("TechnicalDocumentPath")
                        .HasColumnType("text");

                    b.Property<long>("TotalCycleCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("XCoordinate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("YCoordinate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Molds");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageFirePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<bool>("CanApproveWorkOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPerformMaintenance")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPerformQualityControl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseDonerKafa")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseDtfMachine")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseGezerKafa")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseInjectionMachine")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMachineCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentMachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentMachineName")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentStationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentWorkOrderNumber")
                        .HasColumnType("text");

                    b.Property<string>("DefaultMachineCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultMachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultMachineName")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPerformanceUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PerformancePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalFirePairs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalWorkingHours")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentMachineId");

                    b.HasIndex("DefaultMachineId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CutQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShippedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("SizeRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CutPairs")
                        .HasColumnType("integer");

                    b.Property<string>("FabricColor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedPairs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductionType")
                        .HasColumnType("text");

                    b.Property<int>("QuantityPairs")
                        .HasColumnType("integer");

                    b.Property<int>("ShippedPairs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MoldId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultBoxQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FoamType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasDTFLabel")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPolibond")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdhesive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFabric")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("StandardCycleTime")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetDensity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoxCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("FabricColor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductionType")
                        .HasColumnType("text");

                    b.Property<int>("QuantityPairs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MoldId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionBoxes");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionBoxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromLocation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionBoxId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantityPairs")
                        .HasColumnType("integer");

                    b.Property<string>("ToLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductionBoxId");

                    b.ToTable("ProductionBoxEvents");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionDowntime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DurationMinutes")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductionStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductionSessionId");

                    b.HasIndex("ProductionStationId");

                    b.ToTable("ProductionDowntimes");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("CuringTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<long?>("CycleNumber")
                        .HasColumnType("bigint");

                    b.Property<int?>("CycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Density")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FirePairs")
                        .HasColumnType("bigint");

                    b.Property<long?>("GoodPairs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OperatorCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<long?>("ProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductionSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductionStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductionSessionId");

                    b.HasIndex("ProductionStationId");

                    b.ToTable("ProductionEvents");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InjectionStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MoldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedPairs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InjectionStationId");

                    b.HasIndex("MoldId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualAverageCuringTimeSeconds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualAverageCycleTimeSeconds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualAverageDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualAveragePairWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualMaterialCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedMaterialCost")
                        .HasColumnType("numeric");

                    b.Property<long>("FirePairs")
                        .HasColumnType("bigint");

                    b.Property<string>("FoamType")
                        .HasColumnType("text");

                    b.Property<long>("GoodPairs")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlannedPairs")
                        .HasColumnType("bigint");

                    b.Property<long>("ProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductionNote")
                        .HasColumnType("text");

                    b.Property<string>("QualityNote")
                        .HasColumnType("text");

                    b.Property<string>("SessionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetCuringTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetCycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetPairWeight")
                        .HasColumnType("numeric");

                    b.Property<long>("TotalCycleCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalDowntimeMinutes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRunningMinutes")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionSessions");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualLastCuringTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualLastCycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CuringExpectedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CuringStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentCycleNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("CyclesSinceLastRelease")
                        .HasColumnType("integer");

                    b.Property<long>("FirePairs")
                        .HasColumnType("bigint");

                    b.Property<long>("GoodPairs")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCycleCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCycleStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastDensity")
                        .HasColumnType("numeric");

                    b.Property<string>("LastFaultReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastNote")
                        .HasColumnType("text");

                    b.Property<decimal?>("LastPairWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastReleaseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoldCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("MoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("MoldName")
                        .HasColumnType("text");

                    b.Property<string>("OperatorCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<long>("ProducedPairs")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionSessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReleaseFrequencyCycles")
                        .HasColumnType("integer");

                    b.Property<int>("StationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetCuringTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetCycleTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDensity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetPairWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MoldId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionSessionId");

                    b.ToTable("ProductionStations");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("StockItemId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InjectionStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedPairs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StationNumberSnapshot")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InjectionStationId");

                    b.HasIndex("MoldId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("StationAssignments");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CriticalQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("LocationCode")
                        .HasColumnType("text");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaximumQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinimumQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("RecipeUsageAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SafetyInfo")
                        .HasColumnType("text");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("numeric");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("text");

                    b.Property<decimal?>("WasteRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("SourceDocumentNo")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentTermDays")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Fixar.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Fixar.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Fixar.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Fixar.Domain.Entities.CuttingRecord", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.CuttingMachine", "CuttingMachine")
                        .WithMany("CuttingRecords")
                        .HasForeignKey("CuttingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuttingMachine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Mold", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany("Molds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Operator", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Machine", "CurrentMachine")
                        .WithMany("CurrentOperators")
                        .HasForeignKey("CurrentMachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fixar.Domain.Entities.Machine", "DefaultMachine")
                        .WithMany("DefaultOperators")
                        .HasForeignKey("DefaultMachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentMachine");

                    b.Navigation("DefaultMachine");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Order", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Mold", "Mold")
                        .WithMany()
                        .HasForeignKey("MoldId");

                    b.HasOne("Fixar.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Mold");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionBox", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Mold", "Mold")
                        .WithMany()
                        .HasForeignKey("MoldId");

                    b.HasOne("Fixar.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Mold");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionBoxEvent", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.ProductionBox", "ProductionBox")
                        .WithMany("Events")
                        .HasForeignKey("ProductionBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionBox");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionDowntime", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.ProductionSession", "ProductionSession")
                        .WithMany("Downtimes")
                        .HasForeignKey("ProductionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.ProductionStation", "ProductionStation")
                        .WithMany("Downtimes")
                        .HasForeignKey("ProductionStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductionSession");

                    b.Navigation("ProductionStation");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionEvent", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.ProductionSession", "ProductionSession")
                        .WithMany("Events")
                        .HasForeignKey("ProductionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.ProductionStation", "ProductionStation")
                        .WithMany("Events")
                        .HasForeignKey("ProductionStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductionSession");

                    b.Navigation("ProductionStation");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionRecord", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.InjectionStation", "InjectionStation")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("InjectionStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Mold", "Mold")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("MoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InjectionStation");

                    b.Navigation("Mold");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionSession", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionStation", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Mold", "Mold")
                        .WithMany()
                        .HasForeignKey("MoldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fixar.Domain.Entities.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fixar.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fixar.Domain.Entities.ProductionSession", "ProductionSession")
                        .WithMany("Stations")
                        .HasForeignKey("ProductionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mold");

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("ProductionSession");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StationAssignment", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.InjectionStation", "InjectionStation")
                        .WithMany()
                        .HasForeignKey("InjectionStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Domain.Entities.Mold", "Mold")
                        .WithMany()
                        .HasForeignKey("MoldId");

                    b.HasOne("Fixar.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InjectionStation");

                    b.Navigation("Mold");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.Material", "Material")
                        .WithMany("StockItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Fixar.Domain.Entities.StockItem", "StockItem")
                        .WithMany("Movements")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Fixar.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Fixar.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.CuttingMachine", b =>
                {
                    b.Navigation("CuttingRecords");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.InjectionStation", b =>
                {
                    b.Navigation("ProductionRecords");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Machine", b =>
                {
                    b.Navigation("CurrentOperators");

                    b.Navigation("DefaultOperators");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Material", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Mold", b =>
                {
                    b.Navigation("ProductionRecords");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.Product", b =>
                {
                    b.Navigation("Molds");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionBox", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionSession", b =>
                {
                    b.Navigation("Downtimes");

                    b.Navigation("Events");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.ProductionStation", b =>
                {
                    b.Navigation("Downtimes");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Fixar.Domain.Entities.StockItem", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
