namespace Fixar.Application.Features.Profitability;

public sealed record ProfitabilityFilter(DateTime? DateFrom, DateTime? DateTo, string Currency = "TRY", Guid? CustomerId = null, Guid? OrderId = null, Guid? ProductId = null, Guid? WorkOrderId = null, string? ProductionType = null, bool IncludeIncomplete = true, int Limit = 10, string? Search = null);
public sealed record WorkOrderProfitabilityDto(Guid WorkOrderId, string WorkOrderNumber, Guid CustomerId, string CustomerName, Guid OrderId, string OrderNumber, Guid ProductId, string ProductCode, string ProductName, string? ProductionType, int PlannedPairs, int ProducedPairs, int GoodPairs, int FirePairs, decimal EstimatedCost, decimal ActualCost, decimal SalesRevenue, decimal GrossProfit, decimal? GrossMarginPercent, decimal? CostPerGoodPair, decimal? SellingPricePerPair, decimal VarianceAmount, decimal? VariancePercent, DateTime SnapshotDate, string SnapshotStatus, string ProfitabilityStatus, decimal DataCompletenessPercent, IReadOnlyList<string> Warnings);
public sealed record CustomerProfitabilityListDto(Guid CustomerId, string CustomerCode, string CustomerName, int OrderCount, int WorkOrderCount, int TotalOrderedPairs, int TotalProducedPairs, int TotalShippedPairs, decimal NetSalesRevenue, decimal TotalActualCost, decimal GrossProfit, decimal? GrossMarginPercent, decimal? AverageRevenuePerPair, decimal? AverageCostPerPair, decimal? AverageProfitPerPair, int TotalFirePairs, decimal? FireRatePercent, decimal AverageDeliveryDelayDays, int OpenOrderCount, int CompletedOrderCount, int LossMakingWorkOrderCount, DateTime? LastOrderDate, DateTime? LatestCostSnapshotDate, decimal DataCompletenessPercent, IReadOnlyList<string> Warnings);
public sealed record OrderProfitabilityListDto(Guid OrderId, string OrderNumber, Guid CustomerId, string CustomerName, DateTime OrderDate, DateTime? DueDate, string Status, string Currency, decimal OrderNetRevenue, decimal AllocatedRevenue, decimal ActualCost, decimal GrossProfit, decimal? GrossMarginPercent, int TotalPairs, int ProducedPairs, int ShippedPairs, decimal CompletionPercent, int WorkOrderCount, int CostedWorkOrderCount, int MissingCostWorkOrderCount, int FirePairs, decimal? FireRatePercent, bool IsLate, int DelayDays, string ProfitabilityStatus, decimal DataCompletenessPercent, IReadOnlyList<string> Warnings);
public sealed record ProductProfitabilityListDto(Guid ProductId, string ProductCode, string ProductName, string? ProductionType, int OrderCount, int CustomerCount, int WorkOrderCount, int ProducedPairs, int GoodPairs, int FirePairs, decimal? FireRatePercent, decimal NetSalesRevenue, decimal ActualCost, decimal GrossProfit, decimal? GrossMarginPercent, decimal? AverageSalesPricePerPair, decimal? AverageActualCostPerPair, decimal? AverageProfitPerPair, decimal? EstimatedVsActualVariancePercent, string? TopCustomer, DateTime? LatestProductionDate, decimal DataCompletenessPercent);
public sealed record ExecutiveProfitabilitySummaryDto(string ReportingCurrency, DateTime DateFrom, DateTime DateTo, decimal TotalNetRevenue, decimal TotalActualCost, decimal TotalGrossProfit, decimal? GrossMarginPercent, int TotalProducedPairs, int TotalGoodPairs, int TotalFirePairs, decimal? FireRatePercent, int TotalShippedPairs, int ActiveOrderCount, int DelayedOrderCount, int ActiveWorkOrderCount, int CompletedWorkOrderCount, int FullyCostedWorkOrderCount, int MissingCostWorkOrderCount, int ProfitableCustomerCount, int LossMakingCustomerCount, int ProfitableOrderCount, int LossMakingOrderCount, decimal? AverageCostPerGoodPair, decimal? AverageRevenuePerPair, decimal? AverageProfitPerPair, string? TopCustomer, string? TopProduct, string? MostProfitableOrder, string? HighestCostVarianceWorkOrder, string? MostDelayedOrder, decimal DataCompletenessPercent, IReadOnlyList<string> Warnings);
public sealed record MonthlyProfitabilityTrendDto(string Month, decimal Revenue, decimal ActualCost, decimal GrossProfit, decimal? GrossMarginPercent, int ProducedPairs, int GoodPairs, int FirePairs, decimal? FireRatePercent, decimal? AverageCostPerPair, decimal? AverageRevenuePerPair, int CompletedWorkOrderCount, int CustomerCount, int OrderCount);
public sealed record CostCategoryBreakdownDto(string Category, decimal Amount, decimal PercentageOfTotalCost, int WorkOrderCount, decimal? TrendVsPreviousPeriod);
public sealed record ProfitabilityTopBottomDto(IReadOnlyList<CustomerProfitabilityListDto> TopCustomers, IReadOnlyList<CustomerProfitabilityListDto> LowestMarginCustomers, IReadOnlyList<OrderProfitabilityListDto> LossMakingOrders, IReadOnlyList<ProductProfitabilityListDto> TopProducts, IReadOnlyList<ProductProfitabilityListDto> HighestFireProducts, IReadOnlyList<WorkOrderProfitabilityDto> HighestVarianceWorkOrders, IReadOnlyList<OrderProfitabilityListDto> MostDelayedOrders, IReadOnlyList<WorkOrderProfitabilityDto> IncompleteWorkOrders);
public sealed record ProfitabilityDataQualityDto(int TotalWorkOrders, int CostedWorkOrders, int MissingCostWorkOrders, int MissingActualConsumptionCount, int MissingMachinePowerCount, int EstimatedOnlyCount, decimal DataCompletenessPercent, IReadOnlyList<string> Warnings);
